### ISSUE TITLE
請問目前有支援 VTT字幕檔嗎?

### ISSUE THREAD

**Issue by LetsMemo** [Jzvd/JZVideo#100]
**需求描述
因應客戶的多語系要求, 需要載入和切換字幕. 如果可以的話看能不能讓用戶自行選擇切換字幕或隱藏字幕.
(估計需要多一個TextView 適時顯示畫面上的語句用)

**其他app是否实现
愛奇藝

感謝您~

**Comment by lipangit** [comment]
字幕subtitle是一个流，它和视频流音频流同级别。你研究一下三个播放内核怎么支持字幕。





---原始邮件---
发件人: "LetsMemo"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 下午2:40
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 請問目前有支援 VTT字幕檔嗎? (#100)




 
**需求描述
 因應客戶的多語系要求, 需要載入和切換字幕. 如果可以的話看能不能讓用戶自行選擇切換字幕或隱藏字幕.
 (估計需要多一個TextView 適時顯示畫面上的語句用)
 
**其他app是否实现
 愛奇藝
