### ISSUE TITLE
How to mute/unmute player?

### ISSUE THREAD

**Issue by uzaysan** [Jzvd/JZVideo#102]
How can I mute or unmute video? I couldn't find anything.

**Comment by Liberations** [comment]
mediaInterface.setVolume()

**Comment by uzaysan** [comment]
@Liberations It will have value between 0 and 1 I guess. Do you know how to get current volume. I have button and that button will mute/unmute player depenbds on it current volume.
How to get current volume of player?

**Comment by uzaysan** [comment]
@Liberations It gives me null pointer exception:

This is how I init my player in recyclerview:
```
holder.masterExoPlayer.setUp(
                            jzDataSource
                            , Jzvd.SCREEN_NORMAL
                            , JZMediaExo.class);
```
And I do this:
                   ` holder.masterExoPlayer.mediaInterface.setVolume(0,0);`

But It give me null pointer exception:

> java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.JZMediaInterface.setVolume(float, float)' on a null object reference

**Comment by lipangit** [comment]
see demo饺子摇摆&nbsp; in&nbsp; smallchangeactivity



---Original---

**Comment by uzaysan** [comment]
If you use `JZMediaExo.class` as media interface setting volume on `onPrepared()` method will not work. Actually I think `onPrepared()` method is never called when using `JZMediaExo.class`

**Comment by minzbox** [comment]
> If you use `JZMediaExo.class` as media interface, setting volume on `onPrepared()` method will not work. Actually I think `onPrepared()` method is never called when using `JZMediaExo.class`

JZMediaExo has some bugs that not update for a long time. If you want to mute/unmute when using this class, do this in onStatePlaying() method

**Comment by uzaysan** [comment]
> > If you use `JZMediaExo.class` as media interface, setting volume on `onPrepared()` method will not work. Actually I think `onPrepared()` method is never called when using `JZMediaExo.class`
> 
> JZMediaExo has some bugs that not update for a long time. If you want to mute/unmute when using this class, do this in onStatePlaying() method

It works now. Thank you.
