### ISSUE TITLE
Jzvd中的onPrepared方法中为何需要对音频文件做个特殊处理？

### ISSUE THREAD

**Issue by lxt-sky** [Jzvd/JZVideo#106]
相关代码：
```java
   public void onPrepared() {
        ...
        if (jzDataSource.getCurrentUrl().toString().toLowerCase().contains("mp3") ||
                jzDataSource.getCurrentUrl().toString().toLowerCase().contains("wav")) {
            onStatePlaying();
        }
    }
```
这产生了一个问题：当一个音频播放后，如果刷新列表，该音频会重播。

**Comment by lipangit** [comment]
demo有这问题吗



---原始邮件---
发件人: "lxt-sky"<notifications@github.com&gt;
发送时间: 2020年4月9日(周四) 晚上9:46
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] Jzvd中的onPrepared方法中为何需要对音频文件做个特殊处理？ (#106)




 
相关代码：
    public void onPrepared() {         ...         if (jzDataSource.getCurrentUrl().toString().toLowerCase().contains("mp3") ||                 jzDataSource.getCurrentUrl().toString().toLowerCase().contains("wav")) {             onStatePlaying();         }     }
 
这产生了一个问题：当一个音频播放后，如果刷新列表，该音频会重播。

**Comment by lxt-sky** [comment]
不是demo中，我在实际项目中播放音频时产生了这个问题，而播放视频不会。在音视频数据列表重新请求完成后，触发了上述提到的方法，从而音频自动重播。

**Comment by lipangit** [comment]
保持关注



---原始邮件---
发件人: "lxt-sky"<notifications@github.com&gt;
发送时间: 2020年4月13日(周一) 下午5:49
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] Jzvd中的onPrepared方法中为何需要对音频文件做个特殊处理？ (#106)




 
不是demo中，我在实际项目中播放音频时产生了这个问题，而播放视频不会。在音视频数据列表重新请求完成后，触发了上述提到的方法，从而音频自动重播。
