### ISSUE TITLE
视频播放时按返回键 奔溃

### ISSUE THREAD

**Issue by ZhetengDashen** [Jzvd/JZVideo#114]

**Comment by ZhetengDashen** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'long tv.danmaku.ijk.media.player.IjkMediaPlayer.getCurrentPosition()' on a null object reference
        at com.aliyun.svideo.paly.JZMediaIjk.getCurrentPosition(JZMediaIjk.java:136)

**Comment by ZhetengDashen** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'long tv.danmaku.ijk.media.player.IjkMediaPlayer.getCurrentPosition()' on a null object reference

JZMediaIjk.getCurrentPosition(JZMediaIjk.java:136)

**Comment by Liberations** [comment]
注意调用时机
