### ISSUE TITLE
建议在全屏的时候自动判断是横屏还是竖屏视频的功能

### ISSUE THREAD

**Issue by 939582415** [Jzvd/JZVideo#115]
建议在全屏的时候自动判断是横屏还是竖屏视频的功能
之前使用的是6.3.4版本，重写onVideoSizeChanged方法加入横竖屏判断的逻辑就可以，更新了7.3.4就不行了

**Comment by 939582415** [comment]
@Override
    public void onVideoSizeChanged() {
//        super.onVideoSizeChanged();
        if (JZMediaManager.textureView != null) {
            if (videoRotation != 0) {
                JZMediaManager.textureView.setRotation(videoRotation);
            }
            Log.e(TAG, "onVideoSizeChanged: " + JZMediaManager.instance().currentVideoWidth + "===" + JZMediaManager.instance().currentVideoHeight);
            JZMediaManager.textureView.setVideoSize(JZMediaManager.instance().currentVideoWidth, JZMediaManager.instance().currentVideoHeight);
            if (JZMediaManager.instance().currentVideoHeight > JZMediaManager.instance().currentVideoWidth) {
                //视频是横屏 旋转方向
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT;

            } else {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE;

            }
//            JZUtils.setRequestedOrientation(getContext(), Jzvd.FULLSCREEN_ORIENTATION);
        }
    }

**Comment by 939582415** [comment]
使用最新的7.3.4的话，会存在问题，全屏播放一个竖屏的，然后再全屏播放一个横屏的，再播放竖屏就显示横屏了；首次计算不出是横竖屏

**Comment by lipangit** [comment]
更新还是有好处，有问题提出来



---原始邮件---
发件人: "CoderQiao"<notifications@github.com&gt;
发送时间: 2020年4月16日(周四) 下午4:11
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 建议在全屏的时候自动判断是横屏还是竖屏视频的功能 (#115)




 
建议在全屏的时候自动判断是横屏还是竖屏视频的功能
 之前使用的是6.3.4版本，重写onVideoSizeChanged方法加入横竖屏判断的逻辑就可以，更新了7.3.4就不行了

**Comment by lipangit** [comment]
新建了一个任务。
在demo中添加根据视频尺寸确定全屏时的屏幕方向，如果视频宽》高进入横屏全屏，否则进入竖屏全屏。
参考demo的orientationActivity。

**Comment by StaticCoder** [comment]
新版的onVideoSizeChanged中已经返回了高度和宽度直接用就行
override fun onVideoSizeChanged(width: Int, height: Int) {
        super.onVideoSizeChanged(width, height)
        if (height > 0 && height > 0) {
            if (height > width) {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
            } else {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
            }

        }
    }

**Comment by lipangit** [comment]
楼上正解

**Comment by zerorooot** [comment]
我用这个继承，但没效果
```java
import android.content.Context;
import android.content.pm.ActivityInfo;
import android.util.AttributeSet;

import cn.jzvd.Jzvd;
import cn.jzvd.JzvdStd;

public class MyJzvdStd extends JzvdStd {

    public MyJzvdStd(Context context) {
        super(context);
    }

    public MyJzvdStd(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void onVideoSizeChanged(int width, int height) {
        super.onVideoSizeChanged(width, height);
        if (height > 0 && width > 0) {
            if (height > width) {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
            } else {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
            }
        }
    }
```
所以使用了一个比较邪门的方法，也是可以的
 ```java
        jzvdStd.setUp("https://jzvd.nathen.cn/c6e3dc12a1154626b3476d9bf3bd7266/6b56c5f0dc31428083757a45764763b0-5287d2089db37e62345123a1be272f8b.mp4"
                , "饺子闭眼睛");
        //预加载
        jzvdStd.startVideoAfterPreloading();
        //全屏
        jzvdStd.gotoFullscreen();
        jzvdStd.fullscreenButton.setOnClickListener(v -> {
            jzvdStd.autoQuitFullscreen();
            if (Jzvd.FULLSCREEN_ORIENTATION == ActivityInfo.SCREEN_ORIENTATION_PORTRAIT) {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
            }else {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
            }
            jzvdStd.gotoFullscreen();
        });
```
虽然不能自动判断切换是否的横竖屏，但可以通过点击全屏按键来手动切换横竖屏
