### ISSUE TITLE
wifi广播注册流程异常

### ISSUE THREAD

**Issue by chenguangtu** [Jzvd/JZVideo#116]
7.2.3版本
偶发
Log:

java.lang.IllegalArgumentException:Receiver not registered: cn.jzvd.JzvdStd$3@702d2bf
--
 android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:780)
 android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1195)
 android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
 cn.jzvd.JzvdStd.unregisterWifiListener(JzvdStd.java:888)
 cn.jzvd.JzvdStd.reset(JzvdStd.java:832)
 cn.jzvd.Jzvd.setCurrentJzvd(Jzvd.java:1035)
 cn.jzvd.Jzvd.startVideo(Jzvd.java:568)
 cn.jzvd.JzvdStd.startVideo(JzvdStd.java:185)

**Comment by lipangit** [comment]
这是个问题

**Comment by lipangit** [comment]
涉及的问题比较深入，添加到[任务列表](https://github.com/Jzvd/JiaoZiVideoPlayer/wiki/%E6%89%BE%E7%82%B9%E4%BA%8B%E5%81%9A%EF%BC%8C%E6%8C%A3%E7%82%B9%E9%A5%BA%E5%AD%90%E5%B8%81)

**Comment by lipangit** [comment]
要做到修改完不再有人反馈这个问题，才算完成

**Comment by tristanyi** [comment]
我也遇到了

**Comment by tristanyi** [comment]
同时也遇到了loading加载一直不消失的bug

**Comment by rockerkekex** [comment]
请问解决了吗？ 碰到了同样的问题

**Comment by rockerkekex** [comment]
> 同时也遇到了loading加载一直不消失的bug

请问这个bug你解决了吗？
