### ISSUE TITLE
视频刚开始加载loading很慢，有时候卡在loading没反应

### ISSUE THREAD

**Issue by maqingwei** [Jzvd/JZVideo#117]
**什么jzvd版本
7.0.3
**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by panjiafang** [comment]
我补充一个：
**什么jzvd版本
7.0.3
**相关log是什么
I/JZVD: onStateNormal  [216009817] 
D/JZVD: addTextureView [216009817] 
I/JZVD: onStatePreparing  [216009817] 
I/JZVD: startVideo
I/chatty: uid=10375(com.letv.android.client.voice) JZVD identical 11 lines
D/JZVD: onInfo what - 10005 extra - 0
D/JZVD: onInfo what - 10006 extra - 0
D/JZVD: onInfo what - 10007 extra - 0
D/JZVD: onInfo what - 10001 extra - 0
I/JZVD: onVideoSizeChanged  [216009817] 
I/JZVD: onVideoSizeChanged  [216009817] 
I/JZVD: onPrepared  [216009817] 
D/JZVD: onInfo what - 10002 extra - 0
D/JZVD: onInfo what - 701 extra - 0
D/JZVD: MEDIA_INFO_BUFFERING_START
I/JZVD: onStatePreparingPlaying  [216009817] 
I/JZVD: onVideoSizeChanged  [216009817] 
D/JZVD: onInfo what - 10004 extra - 0
I/JZVD: onVideoSizeChanged  [216009817] 
I/JZVD: onVideoSizeChanged  [216009817] 
D/JZVD: onInfo what - 10003 extra - 0
D/JZVD: onInfo what - 702 extra - 0
D/JZVD: MEDIA_INFO_BUFFERING_END
D/JZVD: onInfo what - 3 extra - 0
D/JZVD: MEDIA_INFO_VIDEO_RENDERING_START
**demo是否有这个问题
暂未遇到
**自己做了哪些修改

**如何操作复现
循环切换播放源
**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by panjiafang** [comment]
补充一个
**什么jzvd版本
7.0.3
**相关log是什么
I/JZVD: onStateNormal  [216009817] 
D/JZVD: addTextureView [216009817] 
I/JZVD: onStatePreparing  [216009817] 
I/JZVD: startVideo
I/chatty: uid=10375(com.letv.android.client.voice) JZVD identical 11 lines
D/JZVD: onInfo what - 10005 extra - 0
D/JZVD: onInfo what - 10006 extra - 0
D/JZVD: onInfo what - 10007 extra - 0
D/JZVD: onInfo what - 10001 extra - 0
I/JZVD: onVideoSizeChanged  [216009817] 
I/JZVD: onVideoSizeChanged  [216009817] 
I/JZVD: onPrepared  [216009817] 
D/JZVD: onInfo what - 10002 extra - 0
D/JZVD: onInfo what - 701 extra - 0
D/JZVD: MEDIA_INFO_BUFFERING_START
I/JZVD: onStatePreparingPlaying  [216009817] 
I/JZVD: onVideoSizeChanged  [216009817] 
D/JZVD: onInfo what - 10004 extra - 0
I/JZVD: onVideoSizeChanged  [216009817] 
I/JZVD: onVideoSizeChanged  [216009817] 
D/JZVD: onInfo what - 10003 extra - 0
D/JZVD: onInfo what - 702 extra - 0
D/JZVD: MEDIA_INFO_BUFFERING_END
D/JZVD: onInfo what - 3 extra - 0
D/JZVD: MEDIA_INFO_VIDEO_RENDERING_START

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现
循环切换播放源
**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by panjiafang** [comment]
原因分析：
I/JZVD: onStateNormal [216009817]
D/JZVD: addTextureView [216009817]
I/JZVD: onStatePreparing [216009817]
I/JZVD: startVideo
I/chatty: uid=10375(com.letv.android.client.voice) JZVD identical 11 lines
D/JZVD: onInfo what - 10005 extra - 0
D/JZVD: onInfo what - 10006 extra - 0
D/JZVD: onInfo what - 10007 extra - 0
D/JZVD: onInfo what - 10001 extra - 0
I/JZVD: onVideoSizeChanged [216009817]
I/JZVD: onVideoSizeChanged [216009817]
I/JZVD: onPrepared [216009817]

state = 4

D/JZVD: onInfo what - 10002 extra - 0
D/JZVD: onInfo what - 701 extra - 0
D/JZVD: MEDIA_INFO_BUFFERING_START

backUpBufferState = 4

I/JZVD: onStatePreparingPlaying [216009817]

state = 3

I/JZVD: onVideoSizeChanged [216009817]
D/JZVD: onInfo what - 10004 extra - 0
I/JZVD: onVideoSizeChanged [216009817]
I/JZVD: onVideoSizeChanged [216009817]
D/JZVD: onInfo what - 10003 extra - 0
D/JZVD: onInfo what - 702 extra - 0
D/JZVD: MEDIA_INFO_BUFFERING_END

backUpBufferState = 4 没有做处理，此处应该把state置为4

D/JZVD: onInfo what - 3 extra - 0
D/JZVD: MEDIA_INFO_VIDEO_RENDERING_START
此时由于state = 3导致不能调用onStatePlaying

我的修复办法：
D/JZVD: MEDIA_INFO_BUFFERING_END
backUpBufferState = 4 没有做处理，把state置为4

**Comment by lipangit** [comment]
加载慢是播放内核的问题，尝试切换播放内核。


这个log是播放正常的log，卡主怎么回事，如果你用系统的播放内核还卡主，找找服务器的原因。



---原始邮件---
发件人: "panjiafang"<notifications@github.com&gt;
发送时间: 2020年4月25日(周六) 上午9:23
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 视频刚开始加载loading很慢，有时候卡在loading没反应 (#117)




 
我补充一个：
 **什么jzvd版本
 7.0.3
 **相关log是什么
 I/JZVD: onStateNormal  [216009817]
 D/JZVD: addTextureView [216009817]
 I/JZVD: onStatePreparing  [216009817]
 I/JZVD: startVideo
 I/chatty: uid=10375(com.letv.android.client.voice) JZVD identical 11 lines
 D/JZVD: onInfo what - 10005 extra - 0
 D/JZVD: onInfo what - 10006 extra - 0
 D/JZVD: onInfo what - 10007 extra - 0
 D/JZVD: onInfo what - 10001 extra - 0
 I/JZVD: onVideoSizeChanged  [216009817]
 I/JZVD: onVideoSizeChanged  [216009817]
 I/JZVD: onPrepared  [216009817]
 D/JZVD: onInfo what - 10002 extra - 0
 D/JZVD: onInfo what - 701 extra - 0
 D/JZVD: MEDIA_INFO_BUFFERING_START
 I/JZVD: onStatePreparingPlaying  [216009817]
 I/JZVD: onVideoSizeChanged  [216009817]
 D/JZVD: onInfo what - 10004 extra - 0
 I/JZVD: onVideoSizeChanged  [216009817]
 I/JZVD: onVideoSizeChanged  [216009817]
 D/JZVD: onInfo what - 10003 extra - 0
 D/JZVD: onInfo what - 702 extra - 0
 D/JZVD: MEDIA_INFO_BUFFERING_END
 D/JZVD: onInfo what - 3 extra - 0
 D/JZVD: MEDIA_INFO_VIDEO_RENDERING_START
 **demo是否有这个问题
 暂未遇到
 **自己做了哪些修改
 
**如何操作复现
 循环切换播放源
 **什么安卓版本，什么机型
 
**截图或者视频说明情况
