### ISSUE TITLE
列表滑动自动播放始终有问题

### ISSUE THREAD

**Issue by Cazaea** [Jzvd/JZVideo#118]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
什么问题



---原始邮件---
发件人: "X"<notifications@github.com&gt;
发送时间: 2020年4月20日(周一) 中午1:57
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 列表滑动自动播放始终有问题 (#118)




 
**什么jzvd版本
 
**什么播放器内核
 
**相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 
**如何操作复现
 
**什么安卓版本，什么机型
 
**截图或者视频说明情况
