### ISSUE TITLE
Jzvd.SCREEN_NORMAL   为什么在fragment中我的recyclerview列表视频播放的时候轻轻上下滑动列表当前视频就暂停播放了，并且再次点击该条目播放按钮一直转圈无法播放

### ISSUE THREAD

**Issue by liugang0324** [Jzvd/JZVideo#119]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
demo有这问题吗，需要更多信息



---原始邮件---
发件人: "liugang0324"<notifications@github.com&gt;
发送时间: 2020年4月20日(周一) 下午5:25
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] Jzvd.SCREEN_NORMAL   为什么我的recyclerview列表视频播放的时候轻轻上下滑动列表当前视频就暂停播放了，并且再次点击该条目播放按钮一直转圈无法播放 (#119)




 
**什么jzvd版本
 
**什么播放器内核
 
**相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 
**如何操作复现
 
**什么安卓版本，什么机型
 
**截图或者视频说明情况

**Comment by liugang0324** [comment]
视频列表是一个fragment上的recyclerview,完全照搬了demo中recyclerview的代码，但是实际效果是我的列表点击item可正常播放，轻轻上下滑动未滑出当前列表时该条目停止播放，再次点击要不就是一直loading，要不就是只有声音没有图像，点击全屏音视频正常，退出全屏也可正常播放

**Comment by liugang0324** [comment]
> 
> demo有这问题吗，需要更多信息
> […](#)
> ---原始邮件--- 发件人: "liugang0324"<notifications@github.com&gt; 发送时间: 2020年4月20日(周一) 下午5:25 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] Jzvd.SCREEN_NORMAL 为什么我的recyclerview列表视频播放的时候轻轻上下滑动列表当前视频就暂停播放了，并且再次点击该条目播放按钮一直转圈无法播放 (#119) **什么jzvd版本 **什么播放器内核 **相关log是什么 **demo是否有这个问题 **自己做了哪些修改 **如何操作复现 **什么安卓版本，什么机型 **截图或者视频说明情况 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

demo中recyclerview条目播放上滑滑出屏幕后，滑回来可再次播放，下滑滑出屏幕，滑回来后一直转圈无法正常播放

**Comment by lipangit** [comment]
demo亲测没有问题呀，录视频看看，log什么样

**Comment by liugang0324** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nathen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 凌晨0:29
收件人:&nbsp;"Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"爱琴海之恋"<627865992@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Jzvd/JiaoZiVideoPlayer] Jzvd.SCREEN_NORMAL   为什么在fragment中我的recyclerview列表视频播放的时候轻轻上下滑动列表当前视频就暂停播放了，并且再次点击该条目播放按钮一直转圈无法播放 (#119)





 
demo亲测没有问题呀，录视频看看，log什么样
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

SVID_20200421_113547_1.mp4 (19.80M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7b316337400ca2cdbc480f121e39531c0c080705080e5552190253035c14555256524e560101001e05080103080856510552070f38236160627827680a09530304055106670850000105546809170c4300315e&t=exs_ftn_download&code=41c789a3

**Comment by XuEnhao** [comment]
public class PagerLayoutManager extends LinearLayoutManager {
    private PagerSnapHelper mPagerSnapHelper;
    private OnViewPagerListener mOnViewPagerListener;
    private RecyclerView mRecyclerView;
    private OrientationHelper mVerticalHelper;
    private int curCenterPosition = -1;

    public PagerLayoutManager(Context context, int orientation) {
        super(context, orientation, false);
        init();
    }

    public PagerLayoutManager(Context context, int orientation, boolean reverseLayout) {
        super(context, orientation, reverseLayout);
        init();
    }

    private void init() {
        mPagerSnapHelper = new PagerSnapHelper();
    }

    @Override
    public void onAttachedToWindow(RecyclerView view) {
        super.onAttachedToWindow(view);
        mPagerSnapHelper.attachToRecyclerView(view);
        this.mRecyclerView = view;
        mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {

            @Override
            public void onScrollStateChanged(@NonNull RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                View curChild = findCenterView(PagerLayoutManager.this, getVerticalHelper(PagerLayoutManager.this));
                int curIndex = getPosition(curChild);
                if (curIndex != curCenterPosition) {
                    boolean isInit = curCenterPosition == -1;
                    curCenterPosition = curIndex;
                    if (mOnViewPagerListener != null) {
                        mOnViewPagerListener.onPageSelected(curCenterPosition, curCenterPosition == getItemCount() - 1, curChild, isInit);
                    }
                }
            }
        });
    }

    @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
        super.onLayoutChildren(recycler, state);
    }

    /**
     * 设置监听
     *
     * @param listener
     */
    public void setOnViewPagerListener(OnViewPagerListener listener) {
        this.mOnViewPagerListener = listener;
    }


    private View findCenterView(RecyclerView.LayoutManager layoutManager, OrientationHelper helper) {
        int childCount = layoutManager.getChildCount();
        if (childCount == 0) {
            return null;
        } else {
            View closestChild = null;
            int startest = 2147483647;
            for (int i = 0; i < childCount; ++i) {
                View child = layoutManager.getChildAt(i);
                int childStart = Math.abs(helper.getDecoratedStart(child));
                if (childStart < startest) {
                    startest = childStart;
                    closestChild = child;
                }
            }

            return closestChild;
        }
    }

    @NonNull
    private OrientationHelper getVerticalHelper(@NonNull RecyclerView.LayoutManager layoutManager) {
        if (this.mVerticalHelper == null || this.mVerticalHelper.getLayoutManager() != layoutManager) {
            this.mVerticalHelper = OrientationHelper.createVerticalHelper(layoutManager);
        }

        return this.mVerticalHelper;
    }

    public interface OnViewPagerListener {

        void onPageSelected(int position, boolean isBottom, View view, boolean isInit);
    }
}
原因出在pageLayoutManager上上下滑动没做好处理 可以拿这个尝试一下

**Comment by liugang0324** [comment]
首先非常感谢大神的指点，我刚才做了修改后发现列表滑动一卡一卡的，而且那个视频滑上去，再滑下来播放的时候还是只有声音没有画面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"XuEnhao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 上午10:25
收件人:&nbsp;"Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"爱琴海之恋"<627865992@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Jzvd/JiaoZiVideoPlayer] Jzvd.SCREEN_NORMAL   为什么在fragment中我的recyclerview列表视频播放的时候轻轻上下滑动列表当前视频就暂停播放了，并且再次点击该条目播放按钮一直转圈无法播放 (#119)





 
public class PagerLayoutManager extends LinearLayoutManager {
 private PagerSnapHelper mPagerSnapHelper;
 private OnViewPagerListener mOnViewPagerListener;
 private RecyclerView mRecyclerView;
 private OrientationHelper mVerticalHelper;
 private int curCenterPosition = -1;
 public PagerLayoutManager(Context context, int orientation) {     super(context, orientation, false);     init(); } public PagerLayoutManager(Context context, int orientation, boolean reverseLayout) {     super(context, orientation, reverseLayout);     init(); } private void init() {     mPagerSnapHelper = new PagerSnapHelper(); } @Override public void onAttachedToWindow(RecyclerView view) {     super.onAttachedToWindow(view);     mPagerSnapHelper.attachToRecyclerView(view);     this.mRecyclerView = view;     mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {         @Override         public void onScrollStateChanged(@NonNull RecyclerView recyclerView, int newState) {             super.onScrollStateChanged(recyclerView, newState);         }         @Override         public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {             super.onScrolled(recyclerView, dx, dy);             View curChild = findCenterView(PagerLayoutManager.this, getVerticalHelper(PagerLayoutManager.this));             int curIndex = getPosition(curChild);             if (curIndex != curCenterPosition) {                 boolean isInit = curCenterPosition == -1;                 curCenterPosition = curIndex;                 if (mOnViewPagerListener != null) {                     mOnViewPagerListener.onPageSelected(curCenterPosition, curCenterPosition == getItemCount() - 1, curChild, isInit);                 }             }         }     }); } @Override public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {     super.onLayoutChildren(recycler, state); } /**  * 设置监听  *  * @param listener  */ public void setOnViewPagerListener(OnViewPagerListener listener) {     this.mOnViewPagerListener = listener; } private View findCenterView(RecyclerView.LayoutManager layoutManager, OrientationHelper helper) {     int childCount = layoutManager.getChildCount();     if (childCount == 0) {         return null;     } else {         View closestChild = null;         int startest = 2147483647;         for (int i = 0; i < childCount; ++i) {             View child = layoutManager.getChildAt(i);             int childStart = Math.abs(helper.getDecoratedStart(child));             if (childStart < startest) {                 startest = childStart;                 closestChild = child;             }         }         return closestChild;     } } @NonNull private OrientationHelper getVerticalHelper(@NonNull RecyclerView.LayoutManager layoutManager) {     if (this.mVerticalHelper == null || this.mVerticalHelper.getLayoutManager() != layoutManager) {         this.mVerticalHelper = OrientationHelper.createVerticalHelper(layoutManager);     }     return this.mVerticalHelper; } public interface OnViewPagerListener {     void onPageSelected(int position, boolean isBottom, View view, boolean isInit); }  
}
 原因出在pageLayoutManager上上下滑动没做好处理 可以拿这个尝试一下

**Comment by XuEnhao** [comment]
/**
     * 视频切换监听器
     */
    PagerLayoutManager.OnViewPagerListener onViewPagerListener = new PagerLayoutManager.OnViewPagerListener() {

        @Override
        public void onPageSelected(int position, boolean isBottom, View view, boolean isInit) {
            if (isBottom && !isInit) {
                //到最后一个加载第二页
                ToastUtils.showShort("没有更多，请返回课程页发现更多课程");
            }
            if (!isInit) {
                getSaveScheduleData(video.getCurPosition());
            }
            video.removeFromContainer();
            videoPlayController.reset();
            if (view != null && view.getTag() != null && view.getTag() instanceof CourseDetailHolder) {
                curItemHolder = (CourseDetailHolder) view.getTag();
            }
            video.addToContainer((ViewGroup) view, new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
            videoPlayController.setCurPosition(position, adapter.getData(position));
        }
    };
这是我在这个监听里做的处理 要区分一些东西
