### ISSUE TITLE
播放一会儿播放失败，和点击正常播放loading会一直存在不会消失

### ISSUE THREAD

**Issue by lhj1079947827** [Jzvd/JZVideo#122]
**什么jzvd版本
7.3.0
**什么播放器内核
默认播放内核
**相关log是什么
[
![image](https://user-images.githubusercontent.com/20966610/80296054-8728a780-87aa-11ea-9a25-af810fcce9ae.png)
](url)
**demo是否有这个问题
没有问题，
**自己做了哪些修改
无任何修改，直接复制demo中的自定义MyJzvdStd文件
**如何操作复现
正常播放点击视频就会自己复现
**什么安卓版本，什么机型
在华为荣耀手机上，型号KIW-TLOOH，系统版本6.0.1
**截图或者视频说明情况
[
![image](https://user-images.githubusercontent.com/20966610/80296084-c35c0800-87aa-11ea-92cb-50e820c7dac1.png)
](url)
[
![image](https://user-images.githubusercontent.com/20966610/80296091-ce169d00-87aa-11ea-8ee1-ab9f9ccad104.png)
](url)

**Comment by lipangit** [comment]
1004是内核io问题，如果是低概率复现可以接受，或者从视频本身或者服务器找原因。


对于饺子来说出了这个错误，点击重播能播放就是可以。



---原始邮件---
发件人: "lhj1079947827"<notifications@github.com&gt;
发送时间: 2020年4月26日(周日) 上午10:45
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 播放一会儿播放失败，和点击正常播放loading会一直存在不会消失 (#122)




 
**什么jzvd版本
 7.3.0
 **什么播放器内核
 默认播放内核
 **相关log是什么
 
 
 
 **demo是否有这个问题
 没有问题，
 **自己做了哪些修改
 无任何修改，直接复制demo中的自定义MyJzvdStd文件
 **如何操作复现
 正常播放点击视频就会自己复现
 **什么安卓版本，什么机型
 在华为荣耀手机上，型号KIW-TLOOH，系统版本6.0.1
 **截图或者视频说明情况

**Comment by lipangit** [comment]
loading不消失这应该是个bug，重试和普通开始播放没有区别



---原始邮件---
发件人: "lhj1079947827"<notifications@github.com&gt;
发送时间: 2020年4月26日(周日) 上午10:45
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 播放一会儿播放失败，和点击正常播放loading会一直存在不会消失 (#122)




 
**什么jzvd版本
 7.3.0
 **什么播放器内核
 默认播放内核
 **相关log是什么
 
 
 
 **demo是否有这个问题
 没有问题，
 **自己做了哪些修改
 无任何修改，直接复制demo中的自定义MyJzvdStd文件
 **如何操作复现
 正常播放点击视频就会自己复现
 **什么安卓版本，什么机型
 在华为荣耀手机上，型号KIW-TLOOH，系统版本6.0.1
 **截图或者视频说明情况
