### ISSUE TITLE
使用系统的播放引擎播放本地的mp4会黑屏，并且loading一直在转

### ISSUE THREAD

**Issue by ykl522** [Jzvd/JZVideo#123]
jzvdStd.setUp(path, "", Jzvd.SCREEN_NORMAL, JZMediaSystemAssertFolder.class);
path是一个mp4，播放是有声音的，但是屏幕是黑的，其实是在播放中，但是被其它UI挡住了

我改了源码一个地方，播放正常了，不知道会不会有什么其它影响

我的解决方法：
**jzvd.java** 的 **onPrepared**方法里加上一个mp4的条件就好了
if (jzDataSource.getCurrentUrl().toString().toLowerCase().contains("mp3") ||
                jzDataSource.getCurrentUrl().toString().toLowerCase().contains("wma") ||
                jzDataSource.getCurrentUrl().toString().toLowerCase().contains("aac") ||
                jzDataSource.getCurrentUrl().toString().toLowerCase().contains("m4a") ||
                **jzDataSource.getCurrentUrl().toString().toLowerCase().contains("mp4") ||**
                jzDataSource.getCurrentUrl().toString().toLowerCase().contains("wav")) {
            onStatePlaying();
        }

**什么jzvd版本
7.3.0
**什么播放器内核
系统的播放引擎 JZMediaSystemAssertFolder
**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
从loading进入playing状态的标志是图像开始渲染。这里的判断是处理音频的进入playing状态，因为音频没有图像。

你的mp4断点一下这里，如果不走这里，就不会进入playing状态loading就一直显示。
![image](https://user-images.githubusercontent.com/2038071/80486237-6b312b80-898d-11ea-862c-628b3d35106b.png)
