### ISSUE TITLE
小米9全屏无法隐藏底部导航键

### ISSUE THREAD

**Issue by 534365726** [Jzvd/JZVideo#136]
**什么jzvd版本
7.3
**什么播放器内核
自带
**相关log是什么
全屏模式下小米9无法隐藏底部导航键，
**demo是否有这个问题
有
**自己做了哪些修改
修改jzvdJZUtils无效果
**如何操作复现
全屏播放
**什么安卓版本，什么机型
安卓9.0 小米9
**截图或者视频说明情况
[http://img02.sogoucdn.com/app/a/100520146/7d59f70b6cb2856852024a5d6a7013bf](url)

**Comment by lipangit** [comment]
在这款手机下通过什么代码能隐藏底部导航栏，我给它加进库



---原始邮件---
发件人: "534365726"<notifications@github.com&gt;
发送时间: 2020年5月9日(周六) 下午4:34
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 小米9全屏无法隐藏底部导航键 (#136)




 
**什么jzvd版本
 7.3
 **什么播放器内核
 自带
 **相关log是什么
 全屏模式下小米9无法隐藏底部导航键，
 **demo是否有这个问题
 有
 **自己做了哪些修改
 修改jzvdJZUtils无效果
 **如何操作复现
 全屏播放
 **什么安卓版本，什么机型
 安卓9.0 小米9
 **截图或者视频说明情况
 http://img02.sogoucdn.com/app/a/100520146/7d59f70b6cb2856852024a5d6a7013bf

**Comment by xaEHu** [comment]
https://dev.mi.com/console/doc/detail?pId=2229
@lipangit 
![image](https://user-images.githubusercontent.com/46973471/95862999-3b88ab00-0d96-11eb-83a4-f22afa89aeb4.png)

**Comment by lipangit** [comment]
兄弟帮忙研究把他加进来



---原始邮件---
发件人: "侠一胡"<notifications@github.com&gt;
发送时间: 2020年10月13日(周二) 晚上8:54
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JZVideo] 小米9全屏无法隐藏底部导航键 (#136)




 
https://dev.mi.com/console/doc/detail?pId=2229
 @lipangit

**Comment by xaEHu** [comment]
我发现旧版本饺子库的全屏是会自动隐藏掉那个miui底部提示线，新版本不会隐藏。这中间可能修改过全屏规则导致显示了吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jzvd/JZVideo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 凌晨1:17
收件人:&nbsp;"Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送:&nbsp;"古月忧魂"<844572753@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Jzvd/JZVideo] 小米9全屏无法隐藏底部导航键 (#136)





 兄弟帮忙研究把他加进来 
 
 
 
 ---原始邮件--- 
 发件人: "侠一胡"<notifications@github.com&amp;gt; 
 发送时间: 2020年10月13日(周二) 晚上8:54 
 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&amp;gt;; 
 抄送: "Mention"<mention@noreply.github.com&amp;gt;;"Nathen"<1066666651@qq.com&amp;gt;; 
 主题: Re: [Jzvd/JZVideo] 小米9全屏无法隐藏底部导航键 (#136) 
 
 
 
 
   
 https://dev.mi.com/console/doc/detail?pId=2229 
  @lipangit

**Comment by xaEHu** [comment]
那个就是普通的底部导航栏，7.5.0版本全屏连导航栏都不会隐藏了

**Comment by lipangit** [comment]
有正常的版本吗，一起研究一下

---原始邮件---
发件人: "侠一胡"<notifications@github.com&gt;
发送时间: 2020年10月14日(周三) 晚上8:35
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JZVideo] 小米9全屏无法隐藏底部导航键 (#136)




 我发现旧版本饺子库的全屏是会自动隐藏掉那个miui底部提示线，新版本不会隐藏。这中间可能修改过全屏规则导致显示了吧 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Jzvd/JZVideo"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年10月14日(星期三) 凌晨1:17 
 收件人:&amp;nbsp;"Jzvd/JZVideo"<JZVideo@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"古月忧魂"<844572753@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [Jzvd/JZVideo] 小米9全屏无法隐藏底部导航键 (#136) 
 
 
 
 
 
  兄弟帮忙研究把他加进来  
   
   
   
  ---原始邮件---  
  发件人: "侠一胡"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年10月13日(周二) 晚上8:54  
  收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&amp;amp;gt;;  
  抄送: "Mention"<mention@noreply.github.com&amp;amp;gt;;"Nathen"<1066666651@qq.com&amp;amp;gt;;  
  主题: Re: [Jzvd/JZVideo] 小米9全屏无法隐藏底部导航键 (#136)  
   
   
   
   
     
  https://dev.mi.com/console/doc/detail?pId=2229  
   @lipangit

**Comment by xaEHu** [comment]
7.0.4版本全屏会隐藏底部导航栏

**Comment by Liberations** [comment]
解决了么
