### ISSUE TITLE
Youtube palyer官方的封装

### ISSUE THREAD

**Issue by Qdafengzi** [Jzvd/JZVideo#139]
**需求描述

 什么时候把YouTube player也加上，国外环境开发的APP需要调用YouTube官方的api才可以播放YouTube视频资源，就连Google官方的exoplayer也不支持。

**Comment by lipangit** [comment]
youtubeplayer是什么，有其他项目实现的吗



---原始邮件---
发件人: "Qdafengzi"<notifications@github.com&gt;
发送时间: 2020年5月14日(周四) 中午11:31
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] Youtube palyer官方的封装 (#139)




 
**需求描述
 
什么时候把YouTube player也加上，国外环境开发的APP需要调用YouTube官方的api才可以播放YouTube视频资源，就连Google官方的exoplayer也不支持。

**Comment by Qdafengzi** [comment]
> youtubeplayer是什么，有其他项目实现的吗
> […](#)
> ---原始邮件--- 发件人: "Qdafengzi"<notifications@github.com&gt; 发送时间: 2020年5月14日(周四) 中午11:31 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] Youtube palyer官方的封装 (#139) **需求描述 什么时候把YouTube player也加上，国外环境开发的APP需要调用YouTube官方的api才可以播放YouTube视频资源，就连Google官方的exoplayer也不支持。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我在开发国外的视频应用，需要用到YouTube的视频资源，YouTube视频播放器是YouTube官方提供的api，如果用其他第三方不能获取到YouTube视频的真实地址，所以在想有没有集成好的可以使用的YouTubeplayer , 还好我找到一个 封装的实例 https://github.com/PierfrancescoSoffritti/android-youtube-player
