### ISSUE TITLE
在全屏播放完后点重新播放播放不了，一直在转

### ISSUE THREAD

**Issue by JLuani** [Jzvd/JZVideo#150]
在全屏播放完后点重新播放播放不了，一直在转
![企业微信截图_15900467963453](https://user-images.githubusercontent.com/61309940/82535627-b6e48880-9b79-11ea-8e19-387b540f88eb.png)

**Comment by JLuani** [comment]
![image](https://user-images.githubusercontent.com/61309940/82535754-e98e8100-9b79-11ea-8c92-8ef654e90110.png)

**Comment by lipangit** [comment]
用新版

---原始邮件---
发件人: "JLuani"<notifications@github.com&gt;
发送时间: 2020年5月21日(周四) 下午3:43
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 在全屏播放完后点重新播放播放不了，一直在转 (#150)




 
在全屏播放完后点重新播放播放不了，一直在转

**Comment by JLuani** [comment]
> 用新版
> […](#)
> ---原始邮件--- 发件人: "JLuani"<notifications@github.com&gt; 发送时间: 2020年5月21日(周四) 下午3:43 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 在全屏播放完后点重新播放播放不了，一直在转 (#150) 在全屏播放完后点重新播放播放不了，一直在转 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/61309940/82776048-2e692f00-9e7c-11ea-9c4f-58e14ee663dd.png)
换成7.4.0这样子了，proguard-rules有加

**Comment by JLuani** [comment]
而且我按了新版的apk，里面的全屏播放不退出全屏后重新播放也不行，只有声音没有画面

**Comment by 534365726** [comment]
确实有这个问题7.4.1

**Comment by lipangit** [comment]
问题



---原始邮件---
发件人: "534365726"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 下午4:44
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 在全屏播放完后点重新播放播放不了，一直在转 (#150)




 
确实有这个问题7.4.1

**Comment by lipangit** [comment]
问题严重，这就解决



---原始邮件---
发件人: "534365726"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 下午4:44
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 在全屏播放完后点重新播放播放不了，一直在转 (#150)




 
确实有这个问题7.4.1
