### ISSUE TITLE
API文档在哪里

### ISSUE THREAD

**Issue by AttackPangHu** [Jzvd/JZVideo#159]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
过一遍demo，每个activity都进入一次，每个按钮都点一次，比文字类的文档更直观



---原始邮件---
发件人: "AttackPangHu"<notifications@github.com&gt;
发送时间: 2020年6月5日(周五) 晚上9:44
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] API文档在哪里 (#159)




 
**需求描述
 
**其他app是否实现
 
**截图或者小视频说明
