### ISSUE TITLE
拖动进度条导致画面卡住不再播放

### ISSUE THREAD

**Issue by yilylong** [Jzvd/JZVideo#161]
**什么jzvd版本
7.0.5
**什么播放器内核

**相关log是什么

**demo是否有这个问题
有

不知道大家有没有遇到这样的情况，就是在播放的时候拖动进度条超过缓存进度就会卡住不再加载播放。DEMO也试过。如果拖动进度条不超过缓存进度就没事。

**Comment by lipangit** [comment]
需要更多信息



---原始邮件---
发件人: "hailongzhao"<notifications@github.com&gt;
发送时间: 2020年6月10日(周三) 中午11:23
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 拖动进度条导致画面卡住不再播放 (#161)




 
**什么jzvd版本
 7.0.5
 **什么播放器内核
 
**相关log是什么
 
**demo是否有这个问题
 有
 
不知道大家有没有遇到这样的情况，就是在播放的时候拖动进度条超过缓存进度就会卡住不再加载播放。DEMO也试过。如果拖动进度条不超过缓存进度就没事。

**Comment by yilylong** [comment]
用demo就能测试出来  播放开始后 将进度条拉到 缓存进度后面 （还没缓存加载的地方）一点  画面就卡住不动  再怎么拉进度条都没反应了  再拉回到 已经缓冲部分 也不行了  测试手机华为P30

**Comment by lipangit** [comment]
哪个url



---原始邮件---
发件人: "hailongzhao"<notifications@github.com&gt;
发送时间: 2020年6月10日(周三) 下午3:42
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 拖动进度条导致画面卡住不再播放 (#161)




 
用demo就能测试出来  播放开始后 将进度条拉到 缓存进度后面 （还没缓存加载的地方）一点  画面就卡住不动  再怎么拉进度条都没反应了  再拉回到 已经缓冲部分 也不行了  测试手机华为P30

**Comment by yilylong** [comment]
> 哪个url
> […](#)
> ---原始邮件--- 发件人: "hailongzhao"<notifications@github.com&gt; 发送时间: 2020年6月10日(周三) 下午3:42 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 拖动进度条导致画面卡住不再播放 (#161) 用demo就能测试出来 播放开始后 将进度条拉到 缓存进度后面 （还没缓存加载的地方）一点 画面就卡住不动 再怎么拉进度条都没反应了 再拉回到 已经缓冲部分 也不行了 测试手机华为P30 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

随便给一个吧https://video.21jingji.com/5b27860c328e4f368fedb5a9769d2c31/4a679dd74a03424bb2ad0d5c5bd3d11b-5287d2089db37e62345123a1be272f8b.mp4

**Comment by dongfangmingjia** [comment]
这个问题解决了吗
