### ISSUE TITLE
请问播放器支持精准seek吗？谢谢

### ISSUE THREAD

**Issue by microgogo** [Jzvd/JZVideo#163]
如题

**Comment by lipangit** [comment]
好像和视频关键帧有关系，所以15秒一下的视频不要去seek



---原始邮件---
发件人: "microgogo"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 上午6:09
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 请问播放器支持精准seek吗？谢谢 (#163)




 
如题

**Comment by wangzixu5678** [comment]
MediaPlayer.seekTo(mCurrentDuration, MediaPlayer.SEEK_CLOSEST); 现在有这种模式可以精准定位

**Comment by lipangit** [comment]
什么播放内核
