### ISSUE TITLE
关于changeUrl函数

### ISSUE THREAD

**Issue by Kasarulor** [Jzvd/JZVideo#164]
changeurl切换下一集后显示视频播放失败  MediaPlayerNative: error (1, -2147483648)JZVD: onError 1 - -2147483648 [24005852]   查了下错误码 可能是格式问题 但是我吧这个视频单独播放没有问题

**Comment by lipangit** [comment]
changeurl相当于重新播放一个链接&nbsp; 然后seekto进度



---原始邮件---
发件人: "likui1234"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 下午5:50
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 关于changeUrl函数 (#164)




 
changeurl切换下一集后显示视频播放失败  MediaPlayerNative: error (1, -2147483648)JZVD: onError 1 - -2147483648 [24005852]   查了下错误码 可能是格式问题 但是我吧这个视频单独播放没有问题

**Comment by likui1234** [comment]
然后 调用seekto吗

**Comment by likui1234** [comment]
真的不好意思   我没太明白你的意思 或者说你的回答 让我很懵 首先changeUrl是相当于切换下一个播放链接 然后如果=0 的话相当于开始播放   代码上我也是这么调用的   但是bug显示的是error (1, -2147483648)JZVD: onError 1 - -2147483648 [24005852]   也就是调用了changeUrl之后会在onstateErro中回调

**Comment by likui1234** [comment]
@lipangit 真的不好意思 我没太明白你的意思 或者说你的回答 让我很懵 首先changeUrl是相当于切换下一个播放链接 然后如果=0 的话相当于开始播放 代码上我也是这么调用的 但是bug显示的是error (1, -2147483648)JZVD: onError 1 - -2147483648 [24005852] 也就是调用了changeUrl之后会在onstateErro中回调

**Comment by lipangit** [comment]
你把你的url放到demo里，里面有个切换清晰度的例子，试试



---原始邮件---
发件人: "likui1234"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 晚上6:53
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 关于changeUrl函数 (#164)




 
@lipangit 真的不好意思 我没太明白你的意思 或者说你的回答 让我很懵 首先changeUrl是相当于切换下一个播放链接 然后如果=0 的话相当于开始播放 代码上我也是这么调用的 但是bug显示的是error (1, -2147483648)JZVD: onError 1 - -2147483648 [24005852] 也就是调用了changeUrl之后会在onstateErro中回调

**Comment by likui1234** [comment]
@lipangit   以确定问题所在 代码是没有问题的  我换了在线的地址就没问题  一单用本地文件路径就存在问题了

**Comment by lipangit** [comment]
本地路径seek进度有没有问题



---原始邮件---
发件人: "likui1234"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 晚上8:09
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 关于changeUrl函数 (#164)




 
@lipangit   以确定问题所在 代码是没有问题的  我换了在线的地址就没问题  一单用本地文件路径就存在问题了

**Comment by likui1234** [comment]
@lipangit  都是0啊  直接seekto0 的  本地播放还是不行
    Log.e("JZVD", "当前播放视频为:${index}地址为:${data!![index]}")
            currentUrl=data!![index]
            CURRENT_JZVD.seekToInAdvance=0
            changeUrl(JZDataSource(currentUrl,""), 0)
开始没用直接seekto   直接调用changeurl  都不行  只有在线播放changeurl才不会报错

**Comment by likui1234** [comment]
@lipangit    比如abc 三个视频  进入播放先播放a  成功  完成进入b 失败   异常进入c c失败  又会重头开始循环  a成功   b失败c失败  一直这样循环    bc一直错
