### ISSUE TITLE
怎么实现无缝播放呢？

### ISSUE THREAD

**Issue by 939582415** [Jzvd/JZVideo#166]
怎么实现无缝播放呢？

**Comment by lipangit** [comment]
哪个无缝



---原始邮件---
发件人: "CoderQiao"<notifications@github.com&gt;
发送时间: 2020年6月12日(周五) 上午9:38
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 怎么实现无缝播放呢？ (#166)




 
怎么实现无缝播放呢？

**Comment by Liberations** [comment]
参考Demo
