### ISSUE TITLE
使用IJK播放视频可能会出现有画面无声音情况

### ISSUE THREAD

**Issue by BaiShou** [Jzvd/JZVideo#167]
**什么jzvd版本
7.4.1
**什么播放器内核
IJK
**相关log是什么
`Stream #0: not enough frames to estimate rate; consider increasing probesize`
**demo是否有这个问题
有
**自己做了哪些修改
没有修改，只是单纯的把IJK的SO库换了一下，支持HTTPS
**如何操作复现
播放一些视频就可能出现
**什么安卓版本，什么机型
小米note3  android9.0
**截图或者视频说明情况

出现这个问题，是因为`JZMediaIjk`内部配置了
` ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 1024 * 10);`

**Comment by lipangit** [comment]
把它删掉可以吗

**Comment by BaiShou** [comment]
去掉是可行的

**Comment by wangzhaoyang123** [comment]
@ @BaiShou 我也遇到过这种情况，可以试试逐步增大probesize的值，如果需要播放的视频码率格式都比较不确定的化 可以试试不设置probesize改为设置analyzeduration这个值
