### ISSUE TITLE
recycleview滚动冲突

### ISSUE THREAD

**Issue by AmoyJJ** [Jzvd/JZVideo#168]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:7.4.1
**什么播放器内核
默认
**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况
http://zyzhcs.oss-cn-hangzhou.aliyuncs.com/app/course/task/202006/1592200110-Screenrecorder-2020-06-15-11-46-05-390.mp4

**Comment by lipangit** [comment]
列表什么结构物，有没有嵌套，有没有什么线索思路
