### ISSUE TITLE
在列表里面播放视频，视频地址需要认证，怎么在中间拦截，去执行认证

### ISSUE THREAD

**Issue by easyandroid** [Jzvd/JZVideo#169]
1. 我们的接口返回了一个普通地址 非视频播放地址，点击播放的时候需要走一次认证过程 ,视频认证走接口才返回真正的播放地址。在列表(RecyclerView)中怎么去认证。

**Comment by lipangit** [comment]
继承jzvdstd复写startvideo函数&nbsp; &nbsp;先写你的逻辑，在你的逻辑完成之后调用开始播放的函数

---原始邮件---
发件人: "easyandroid"<notifications@github.com&gt;
发送时间: 2020年6月15日(周一) 下午5:31
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 在列表里面播放视频，视频地址需要认证，怎么在中间拦截，去执行认证 (#169)




  
我们的接口返回了一个普通地址 非视频播放地址，点击播放的时候需要走一次认证过程 ,视频认证走接口才返回真正的播放地址。在列表(RecyclerView)中怎么去认证。

**Comment by easyandroid** [comment]
在 RecyclerView  弱网点击 有两个转圈，认证过程还没有 addTextureView 。

**Comment by lipangit** [comment]
第一步相当于拦截点击事件去做你的事情，这个步骤和视频播放没有任何关系。第二步你的事情做完了开始播放视频。其他的不用关心，两个圈截图看看

**Comment by easyandroid** [comment]
![视频bug](https://user-images.githubusercontent.com/5576002/84723966-83025480-afb9-11ea-9b31-4bfecf0dcd98.jpg) 在弱网加载时 点击。

**Comment by easyandroid** [comment]
![视频bug2](https://user-images.githubusercontent.com/5576002/84724123-e4c2be80-afb9-11ea-82e7-b126e06c99cf.png)
正在加载的时候 点击

**Comment by lipangit** [comment]
这个loading控件是哪来的，饺子只有loading和非loading，弱联网也是loading，没有中间选项



---原始邮件---
发件人: "easyandroid"<notifications@github.com&gt;
发送时间: 2020年6月16日(周二) 上午10:10
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 在列表里面播放视频，视频地址需要认证，怎么在中间拦截，去执行认证 (#169)




 
 在弱网加载时 点击。

**Comment by easyandroid** [comment]
![bug3](https://user-images.githubusercontent.com/5576002/84724631-3a4b9b00-afbb-11ea-8886-096a4e6a28f8.jpg)
我换回之前的 就是说 认证的时候 我把loadingProgressBar.setVisibility(VISIBLE); 显示了 。
