### ISSUE TITLE
最新版Demo  Pixel3   Android 10 本地视频播放失败   

### ISSUE THREAD

**Issue by yrickwong** [Jzvd/JZVideo#170]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by yrickwong** [comment]
play local 的就跪了 一直loading  play assert的没问题

**Comment by Liberations** [comment]
检查下日志有啥报错 或者警告

**Comment by gaohequan** [comment]
是不是安卓10的原因，解决了么？

**Comment by Liberations** [comment]
检查是否url地址错误 高版本url需要用fileprovider
