### ISSUE TITLE
进度条拖到最后，自动切换下一个视频，可能会出现progressBar不动

### ISSUE THREAD

**Issue by BaiShou** [Jzvd/JZVideo#173]
**什么jzvd版本
7.4.1
**什么播放器内核
IJK
**相关log是什么

**demo是否有这个问题

**自己做了哪些修改
没有修改，使用`changeUrl`切换视频
**如何操作复现
progressBar拖动到最后，自动切换下一部视频，就可能出现progressBar不动，时间也不动
**什么安卓版本，什么机型
小米note3，android:9.0
**截图或者视频说明情况
查看JZVD中 seekToManulPosition  一直处于100，导致`void onProgress(int progress, long position, long duration)`方法一直被return

**Comment by lipangit** [comment]
收到



---原始邮件---
发件人: "Arnold"<notifications@github.com&gt;
发送时间: 2020年6月18日(周四) 上午10:31
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 进度条拖到最后，自动切换下一个视频，可能会出现progressBar不动 (#173)




 
**什么jzvd版本
 7.4.1
 **什么播放器内核
 IJK
 **相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 没有修改，使用changeUrl切换视频
 **如何操作复现
 progressBar拖动到最后，自动切换下一部视频，就可能出现progressBar不动，时间也不动
 **什么安卓版本，什么机型
 小米note3，android:9.0
 **截图或者视频说明情况
 查看JZVD中 seekToManulPosition  一直处于100，导致void onProgress(int progress, long position, long duration)方法一直被return

**Comment by androidwt** [comment]
再播放完成的监听下  添加seekToManulPosition = -1;   将拖动进度重置为-1即可  具体原因应该是onProgress监听的时候 有掉帧情况
