### ISSUE TITLE
Null Pointer Exception While scrolling the recyclerview 

### ISSUE THREAD

**Issue by Mayank1904** [Jzvd/JZVideo#177]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

feedsRecView.addOnChildAttachStateChangeListener(object : RecyclerView.OnChildAttachStateChangeListener {
            override fun onChildViewAttachedToWindow(view: View) {
            }

            override fun onChildViewDetachedFromWindow(view: View) {
                val jzvd = view.findViewById<Jzvd>(R.id.feedVideoPlayerLayout)
                if ((jzvd != null && Jzvd.CURRENT_JZVD != null &&
                            jzvd?.jzDataSource?.containsTheUrl(Jzvd.CURRENT_JZVD?.jzDataSource?.currentUrl)!!)
                ) {
                    if (Jzvd.CURRENT_JZVD != null && Jzvd.CURRENT_JZVD.screen != Jzvd.SCREEN_FULLSCREEN) {
                        Jzvd.releaseAllVideos()
                    }
                }
            }
        })

jzvd?.jzDataSource is getting null while scroll

**Comment by lipangit** [comment]
能提交一个pr吗



---Original---

**Comment by Mayank1904** [comment]
Now I solved the issue with change in the condition

if ((jzvd != null && Jzvd.CURRENT_JZVD != null && jzvd.jzDataSource != null &&
                            jzvd?.jzDataSource?.containsTheUrl(Jzvd.CURRENT_JZVD?.jzDataSource?.currentUrl)!!)
                ) {
                    if (Jzvd.CURRENT_JZVD != null && Jzvd.CURRENT_JZVD.screen != Jzvd.SCREEN_FULLSCREEN) {
                        Jzvd.releaseAllVideos()
                    }
                }
