### ISSUE TITLE
m3u8格式的视频 没法截GIF图？

### ISSUE THREAD

**Issue by ShawnLuo110** [Jzvd/JZVideo#180]
m3u8格式的视频 没法截GIF图？  大佬指教

**Comment by minorlai** [comment]
我也遇到这个问题，m3u8格式的地址无法播放

**Comment by minorlai** [comment]
@felipetorres @ANPez @MickeyBadBad 
这么解决呢？

**Comment by lipangit** [comment]
保持关注



---原始邮件---
发件人: "EDriving"<notifications@github.com&gt;
发送时间: 2020年6月25日(周四) 中午12:05
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] m3u8格式的视频 没法截GIF图？ (#180)




 
m3u8格式的视频 没法截GIF图？  大佬指教

**Comment by lexluthors** [comment]
m3u8播放的时候点击进度条,就无法播放了.求修复

**Comment by lipangit** [comment]
取决于播放内核  超出本库解决范围  @lexluthors
