### ISSUE TITLE
打不开如下的视频流文件

### ISSUE THREAD

**Issue by ChristianXjf** [Jzvd/JZVideo#182]
http://47.101.58.139:3040/api/download?id=2c93099372cba0e00172e626d072046f

**Comment by ChristianXjf** [comment]
控制台打印出的错误日志：E/IMGSRV: texmgmt.c:4039: IsTextureConsistent: IMGEGLImage is not consistent

**Comment by lipangit** [comment]
超出本库解决范围



---原始邮件---
发件人: "ChristianXjf"<notifications@github.com&gt;
发送时间: 2020年6月28日(周日) 下午4:57
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 打不开如下的视频流文件 (#182)




 
控制台打印出的错误日志：E/IMGSRV: texmgmt.c:4039: IsTextureConsistent: IMGEGLImage is not consistent
