### ISSUE TITLE
视频没有x0.5  x1 x1.5 x2倍速播放 请加入进去

### ISSUE THREAD

**Issue by yuzhongrong** [Jzvd/JZVideo#184]
**需求描述
视频没有倍速播放

**其他app是否实现
其他app这个属于最普通功能

**截图或者小视频说明
不用截图了

**Comment by lipangit** [comment]
demo中有这个例子，全屏之后能看到



---原始邮件---
发件人: "yuzhongrong"<notifications@github.com&gt;
发送时间: 2020年6月28日(周日) 晚上9:17
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 视频没有x0.5  x1 x1.5 x2倍速播放 请加入进去 (#184)




 
**需求描述
 视频没有倍速播放
 
**其他app是否实现
 其他app这个属于最普通功能
 
**截图或者小视频说明
 不用截图了

**Comment by liyuhaolol** [comment]
> 

您好，demo里并不能找到倍速的例子
