### ISSUE TITLE
视频播放过程中经常出现加载失败

### ISSUE THREAD

**Issue by yuzhongrong** [Jzvd/JZVideo#185]
**什么jzvd版本

7.4.1
**什么播放器内核
直接播放模式默认内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改
没有做任何修改
**如何操作复现

**什么安卓版本，什么机型
华为 10.0
[**截图或者视频说明情况](http://note.youdao.com/s/M9wkv5DB)

**Comment by lipangit** [comment]
取决于播放内核，换内核试试



---原始邮件---
发件人: "yuzhongrong"<notifications@github.com&gt;
发送时间: 2020年6月28日(周日) 晚上11:59
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 视频播放过程中经常出现加载失败 (#185)




 
**什么jzvd版本
 
7.4.1
 **什么播放器内核
 直接播放模式默认内核
 
**相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 没有做任何修改
 **如何操作复现
 
**什么安卓版本，什么机型
 华为 10.0
 **截图或者视频说明情况

**Comment by yuzhongrong** [comment]
好的谢谢我换一个试试

**Comment by yuzhongrong** [comment]
不行 我切换了ijk的库还是不行只不过比原来效果好一些

**Comment by yuzhongrong** [comment]
还存在这个问题 不放弃不稳当

**Comment by yuzhongrong** [comment]
![20A6AEC40A1118AAA0BE5A466017CB49](https://user-images.githubusercontent.com/7382234/86097173-deb6fc80-bae6-11ea-9b63-d25203ef310a.jpg)

**Comment by yuzhongrong** [comment]
还是失败 切换到ijk核心后 还是失败 这个播放器到底行不行

**Comment by yuzhongrong** [comment]
和so库有关系吗 我没有集成so库

**Comment by yuzhongrong** [comment]
有没有人可以回到下

**Comment by yuzhongrong** [comment]
抓紧看下把很影响用户体验

**Comment by lipangit** [comment]
可以研究一下服务器和视频本身，总最常规的东西比较稳定。

还有exoplayer试试，如果还不行超出本库解决范围了。
