### ISSUE TITLE
作者可以考虑重构下这个库了，所有功能都集中在几个类明显不利于扩展的

### ISSUE THREAD

**Issue by w290721955** [Jzvd/JZVideo#187]
**需求描述
这几天尝试用作者这个库定制下播放器，发现一点点不一样需要改动的地方很多，很多不需要的功能混合在一起。可以考虑把核心功能独立下，剩下的列表循环、集数显示、列表显示什么的做为扩展。模块化更利于后期功能扩展。
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
正在酝酿一次大改版。将标准的jzvd分为三个类可供继承。简单 中等&nbsp; 和复杂。



---原始邮件---
发件人: "w290721955"<notifications@github.com&gt;
发送时间: 2020年6月29日(周一) 下午3:48
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 作者可以考虑重构下这个库了，所有功能都集中在几个类明显不利于扩展的 (#187)




 
**需求描述
 这几天尝试用作者这个库定制下播放器，发现一点点不一样需要改动的地方很多，很多不需要的功能混合在一起。可以考虑把核心功能独立下，剩下的列表循环、集数显示、列表显示什么的做为扩展。
 **其他app是否实现
 
**截图或者小视频说明

**Comment by lipangit** [comment]
兄弟重构方面有什么想法可以描述一下

**Comment by w290721955** [comment]
作者这个库目前功能已经比较全了，主要是要所有功能太集中了，对于使用的人需求一般都不会相同，都需要修改一些，定制一些。我目前的想法是作者可以把UI操作也抽象一下，像抽象播放器一样(JZMediaInterface)，可以把播放器UI操作的一些基础操作先抽象一版，然后再慢慢在基础版上再继承抽象其他版本，这样谁需要什么样的版本继承相应版本就行，也让使用的人可以有不同的选择和扩展。主要是核心基础版需要抽象好，后面的版本就好做。

**Comment by lipangit** [comment]
感谢你的反馈，你的建议非常中肯和靠谱，给你1000个jzt，加我微信。下一个kt版本几个月前做出如下计划。把library中的jzvdstd分为三个标准的类，

分别为简单ui，参考快手抖音。
标准ui， 现在的头条或者西瓜视频
复杂ui， 参考腾讯优酷爱奇艺。

根据自己的需求去继承和自己ui相关的类。
