### ISSUE TITLE
Glide.with(this).load("http://jzvd-pic.nathen.cn/jzvd-pic/1bb2ebbe-140d-4e2e-abd2-9e7e564f71ac.png").into(myJzvdStd.thumbImageView);  。

### ISSUE THREAD

**Issue by yuzhongrong** [Jzvd/JZVideo#189]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

myJzvdStd.thumbImageView   zvdStd中并没有这个控件thumbImageView

**Comment by tao111222333444** [comment]
你依赖的版本是  7.4.1版本吗 ？    在这个版本 myJzvdStd.thumbImageView 已经改成   myJzvdStd.posterImageView 这个了
