### ISSUE TITLE
demo中AGVideo必须setUp后就调用startVideo 将此方法移至点击事件视频就无法播放 但是有声音

### ISSUE THREAD

**Issue by KingCold** [Jzvd/JZVideo#191]
**什么jzvd版本
        implementation 'cn.jzvd:jiaozivideoplayer:7.4.2'
**什么播放器内核
        implementation 'com.google.android.exoplayer:exoplayer:2.10.4'
**相关log是什么

**demo是否有这个问题
有
**自己做了哪些修改
去掉一些控件包括AGVideo中的投屏 加速 选集 前进15秒 后退15秒
**如何操作复现
在demo AGVideoActivity 布局中添加一个控件 将mPlayer.startVideo();方法移至此控件点击事件中
**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
已转发给作者



---原始邮件---
发件人: "KingCold"<notifications@github.com&gt;
发送时间: 2020年7月2日(周四) 中午11:46
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] demo中AGVideo必须setUp后就调用startVideo 将此方法移至点击事件视频就无法播放 但是有声音 (#191)




 
**什么jzvd版本
 implementation 'cn.jzvd:jiaozivideoplayer:7.4.2'
 **什么播放器内核
 implementation 'com.google.android.exoplayer:exoplayer:2.10.4'
 **相关log是什么
 
**demo是否有这个问题
 有
 **自己做了哪些修改
 去掉一些控件包括AGVideo中的投屏 加速 选集 前进15秒 后退15秒
 **如何操作复现
 在demo AGVideoActivity 布局中添加一个控件 将mPlayer.startVideo();方法移至此控件点击事件中
 **什么安卓版本，什么机型
 
**截图或者视频说明情况

**Comment by lipangit** [comment]
解决了吗

**Comment by ToxicR** [comment]
Demo中无法复现你所形容的问题，请对比Demo和自己的项目细节上有没有区别
