### ISSUE TITLE
自定义界面全屏播放视频后返回吞标题

### ISSUE THREAD

**Issue by 534365726** [Jzvd/JZVideo#192]
**什么jzvd版本
7.4.2
**什么播放器内核
自带
**相关log是什么
无
**demo是否有这个问题
有
**自己做了哪些修改
等待大佬修改
**如何操作复现
全屏播放自定义界面列表视频后返回
**什么安卓版本，什么机型
安卓10 小米9
**截图或者视频说明情况

**Comment by lipangit** [comment]
截图看看，需要更多信息，啥症状没看懂
