### ISSUE TITLE
调用backPress()方法偶发崩溃

### ISSUE THREAD

**Issue by jackewu** [Jzvd/JZVideo#193]
java.lang.IllegalStateException
The specified child already has a parent. You must call removeView() on the child's parent first.
android.view.ViewGroup.addViewInner(ViewGroup.java:5326)
 android.view.ViewGroup.addView(ViewGroup.java:5155)
 cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1001)
cn.jzvd.Jzvd.backPress(Jzvd.java:223)

**Comment by lipangit** [comment]
保持关注



---原始邮件---
发件人: "jackewu"<notifications@github.com&gt;
发送时间: 2020年7月2日(周四) 晚上9:37
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 调用backPress()方法偶发崩溃 (#193)




 
java.lang.IllegalStateException
 The specified child already has a parent. You must call removeView() on the child's parent first.
 android.view.ViewGroup.addViewInner(ViewGroup.java:5326)
 &nbsp;android.view.ViewGroup.addView(ViewGroup.java:5155)
 &nbsp;cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1001)
 cn.jzvd.Jzvd.backPress(Jzvd.java:223)

**Comment by Liujinliang0803** [comment]
Stack trace:  
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5326)
	at android.view.ViewGroup.addView(ViewGroup.java:5155)
	at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1004)
	at cn.jzvd.Jzvd.backPress(Jzvd.java:234)

> 保持关注
> […](#)
> ---原始邮件--- 发件人: "jackewu"<notifications@github.com&gt; 发送时间: 2020年7月2日(周四) 晚上9:37 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JZVideo] 调用backPress()方法偶发崩溃 (#193) java.lang.IllegalStateException The specified child already has a parent. You must call removeView() on the child's parent first. android.view.ViewGroup.addViewInner(ViewGroup.java:5326) &nbsp;android.view.ViewGroup.addView(ViewGroup.java:5155) &nbsp;cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1001) cn.jzvd.Jzvd.backPress(Jzvd.java:223) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lipangit** [comment]
有思路吗

**Comment by DreamerLeon** [comment]
遇到了相同的问题

> Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5259)
       at android.view.ViewGroup.addView(ViewGroup.java:5090)
       at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1001)
       at cn.jzvd.Jzvd.backPress(Jzvd.java:223)

**Comment by DreamerLeon** [comment]
> 有思路吗

似乎是全屏播放视频的时候播放结束默认会自动返回非全屏的状态，但是发生这个问题的时候并没有自动返回非全屏状态，此时点击返回按钮会发生奔溃

**Comment by lipangit** [comment]
有道理  保持关注

**Comment by jinlinupup** [comment]
+1

**Comment by jinlinupup** [comment]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5105)
    at android.view.ViewGroup.addView(ViewGroup.java:4936)
    at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1014)
    at cn.jzvd.Jzvd.backPress(Jzvd.java:234)

**Comment by yslxl-99** [comment]
+1

**Comment by xxxifan** [comment]
也遇到这个问题，看到注释说

`如果全屏或者返回全屏的视图有问题，复写这两个函数gotoScreenNormal(),根据自己布局的情况重新布局。`

并且我的问题是发生在 removeViewAt的时候。
暂时不清楚这里的用意，没办法去复写方法。

**Comment by Liberations** [comment]
试试新版

**Comment by NingJinBo** [comment]
+1
