### ISSUE TITLE
一键切换内核里的AGVideo是干嘛的。。为什么要加在exo的类里呢。。。这个耦合度太高了

### ISSUE THREAD

**Issue by huanghaoming** [Jzvd/JZVideo#194]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
这个是完全自定义ui的例子，他和exo没有直接关系，怎么耦合了

**Comment by huanghaoming** [comment]
> 这个是完全自定义ui的例子，他和exo没有直接关系，怎么耦合了

谢谢你的回复。。是这样的。。。我在尝试切换exo的内核。。然后根据你的demo来。。
   jzvdStd.setUp("http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4"
                , "饺子追星", JzvdStd.SCREEN_NORMAL, JZMediaExo.class);

问题是： JZMediaExo.class这个类里面。。为什么还要有一些AGVideo的类。。。

**Comment by lipangit** [comment]
这不应该

**Comment by ToxicR** [comment]
已修改
