### ISSUE TITLE
获取加载速度

### ISSUE THREAD

**Issue by scb7709** [Jzvd/JZVideo#196]
**需求描述
加载中卡转圈的时候，展示网速
**其他app是否实现
都有实现

**截图或者小视频说明
爱奇艺，腾讯，优酷等都有实现

**Comment by lipangit** [comment]
这个需求可以有

**Comment by lipangit** [comment]
从播放内核取得，找一下api



---原始邮件---
发件人: "scb7709"<notifications@github.com&gt;
发送时间: 2020年7月6日(周一) 下午5:36
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 获取加载速度 (#196)




 
**需求描述
 
**其他app是否实现
 
**截图或者小视频说明
 加载中卡转圈的时候，展示网速，怎么获取当前网速
