### ISSUE TITLE
饺子demo中，设置使用ijkplayer内核，重复循环播放同一视频的时候，封面和缓冲加载框会出现，视频重新缓冲了

### ISSUE THREAD

**Issue by dlihasa** [Jzvd/JZVideo#200]
**什么jzvd版本
7.4.0
**什么播放器内核
ijkplayer
**相关log是什么

**demo是否有这个问题
demo中存在此问题
**自己做了哪些修改
<img width="632" alt="image" src="https://user-images.githubusercontent.com/19769208/87129488-00249f00-c2c4-11ea-9dfb-5203d81b8882.png">

**如何操作复现
如上，在demo下JZMediaIjk类的代码中添加框起来的代码（参数为true）进行循环播放
**什么安卓版本，什么机型
无需特定版本和机型
**截图或者视频说明情况

**Comment by lipangit** [comment]
取决于播放内核的逻辑
