### ISSUE TITLE
列表自动播放最后2个始终播放不了，同时在if(positionInList != i + firstVisiblePosition)里是否应该加上positionInList = i+firstVisiblePosition;

### ISSUE THREAD

**Issue by moo611** [Jzvd/JZVideo#201]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by Liberations** [comment]
自动播放只是播放屏幕中第一个可见的视频。最后三个都可见那就播放倒数第三个。你可以自己修改代码控制。
