### ISSUE TITLE
自定义时重复播放失败

### ISSUE THREAD

**Issue by zhenghow** [Jzvd/JZVideo#202]
**什么jzvd版本    
7.2.4  更新 7.4.2也有

**什么播放器内核   
默认

**相关log是什么  
不会出现log

**demo是否有这个问题     
 demo也会出现，demo的视频时间过长，使用的22秒的视频进行测试

**自己做了哪些修改   
 使用的高度自定义的AGVideo

**如何操作复现     
进行视频播放不进行任何操作到视频结束，点击重播，这时会卡住

**什么安卓版本，什么机型
安卓10 , 小米8 , MIUI  11

**截图或者视频说明情况

![fb339e681405289f83ec727aad3bede3](https://user-images.githubusercontent.com/22534617/87903304-3addc280-ca8e-11ea-8209-65bd7e448754.jpg)

![image](https://user-images.githubusercontent.com/22534617/87903362-652f8000-ca8e-11ea-91a4-5047dd0f115a.png)

好像是  AGVideo 中R.id.replay_text重播按钮的 mediaInterface.seekTo(0);没有实现，视频中修改成 mediaInterface.seekTo(1);第一次重播可以实现，但是第二次就会卡住。如果对视频进度进行调整就不会出现这个卡住的问题

**Comment by lipangit** [comment]
mediaInterface.seekTo(1);  这样就不会卡顿是吗
