### ISSUE TITLE
通过设置seekToInAdvance的值 无法跳转到指定位置播放

### ISSUE THREAD

**Issue by wangcaiwen5** [Jzvd/JZVideo#204]
**什么安卓版本，什么机型
华为FRD-AL10 android8.0.0

通过设置seekToInAdvance的值 无法跳转到指定位置播放 目前其他手机上可以  暂时就发现华为FRD-AL10 android8.0.0  不行

**Comment by lipangit** [comment]
取决于播放内核。时间短的视频跳转位置不准确。
