### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by AmoyJJ** [Jzvd/JZVideo#205]
**什么jzvd版本   7.4.1

1	android.view.ViewGroup.addViewInner(ViewGroup.java:5168)
2	android.view.ViewGroup.addView(ViewGroup.java:4997)
3	cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1001)
4	cn.jzvd.Jzvd.backPress(Jzvd.java:223)

**Comment by lipangit** [comment]
这是个问题，需要解决。  保持关注，没有思路。
