### ISSUE TITLE
Subtitle Support

### ISSUE THREAD

**Issue by nidhinprathap** [Jzvd/JZVideo#207]
**Add support for subtitles
Appreciate your work on library, but don't see a way to add/support Subtitles. Nowadays it's a common  feature.

**Comment by lipangit** [comment]
give me  a video  file with subtitle. i will test it.
and you can change to exoplayer or ijkplayer.

**Comment by reedniv** [comment]
Yeah, now video player must support auto subtitle detection

**Comment by nidhinprathap** [comment]
Have completely switched to ExoPlayer now
