### ISSUE TITLE
全屏非播放状态，切换至半屏会自动重播或者继续播放

### ISSUE THREAD

**Issue by androidwt** [Jzvd/JZVideo#208]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by androidwt** [comment]
视频播放完  点击返回键或者取消全屏  会自动重播
视频全屏暂停，同操作会自动恢复播放

**Comment by androidwt** [comment]
I/JZResizeTextureView: onMeasure  [161314421] 
 I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1420]
 I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1200]
 I/JZResizeTextureView: onMeasure  [161314421] 
 I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1920]
 I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1120]
 I/JZResizeTextureView: onMeasure  [161314421] 
 I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1120]
 I/JZResizeTextureView: onMeasure  [161314421] 
 I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1920]
 I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1152]
 I/JZResizeTextureView: onMeasure  [161314421] 
 I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1420]
 I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1152]
 I/JZResizeTextureView: onMeasure  [161314421] 
 I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1920]
 I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1072]
 I/JZResizeTextureView: onMeasure  [161314421] 
 I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1420]
 I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1072]
 D/IJKMEDIA: IjkMediaPlayer_native_setup
 I/IJKMEDIA: av_version_info: ff3.4--ijk0.8.7--20180103--001
 I/IJKMEDIA: ijk_version_info: k0.8.8
 D/IJKMEDIA: ffpipeline_create_from_android()
 D/IJKMEDIA: ijkmp_set_inject_opaque(0x2292)
 D/IJKMEDIA: ijkmp_set_inject_opaque()=void
 D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x2292)
 D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void

**Comment by androidwt** [comment]
全屏播完后，点击返回或者取消全屏，视频自动重播了

**Comment by lipangit** [comment]
demo 是否有这个问题，如何浮现  如何测试

**Comment by cdukuang** [comment]
> demo 是否有这个问题，如何浮现 如何测试

demo有这个问题，改变播放内核界面，播放直播点击全屏等待播放完毕，之后点击返回或者关闭全屏，视频自动播放了
