### ISSUE TITLE
有支持lrc字幕吗

### ISSUE THREAD

**Issue by AmoyJJ** [Jzvd/JZVideo#211]
**需求描述
lrc字幕有支持嘛？
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
取决于播放内核，   给我一个带字幕的链接或者视频 我研究一下，正在研究内核的功能。

**Comment by AmoyJJ** [comment]
不是内置字幕。而是外挂字幕。单独加载lrc之类的字幕文件

**Comment by lipangit** [comment]
取决于播放内核 我没研究过&nbsp; 研究出来可以加进来



---原始邮件---
发件人: "AmoyJJ"<notifications@github.com&gt;
发送时间: 2020年9月8日(周二) 下午2:38
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JZVideo] 有支持lrc字幕吗 (#211)




 
不是内置字幕。而是外挂字幕。单独加载lrc之类的字幕文件
