### ISSUE TITLE
bugly检测到backPress 导致奔溃问题

### ISSUE THREAD

**Issue by BaiShou** [Jzvd/JZVideo#216]
**什么jzvd版本
7.4.2
**什么播放器内核
IJK
**相关log是什么
```
The specified child already has a parent. You must call removeView() on the child's parent first.
```
**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型
三星 SM G9810,Android 10,level 29
**截图或者视频说明情况
<img width="1061" alt="WX20200818-145908@2x" src="https://user-images.githubusercontent.com/7632587/90481069-bc933f80-e163-11ea-9fad-f5d1255e5765.png">

**Comment by lipangit** [comment]
保持关注
