### ISSUE TITLE
自动播放列表，稍微滑动一点点的时时候，视频会暂停播放

### ISSUE THREAD

**Issue by xiangzhenwang** [Jzvd/JZVideo#217]
**什么jzvd版本
7.4.2

**什么播放器内核
所以内核都存在的问题

**demo是否有这个问题
是

**如何操作复现
自动播放列表，稍微滑动一点点的时候，视频就会暂停，轻轻动一下又继续播放，滑动距离很小的时候会出现。

**Comment by lipangit** [comment]
demo哪个页面有这个问题，如何复现，刚测demo列表均无问题。

**Comment by nakisaren** [comment]
> demo哪个页面有这个问题，如何复现，刚测demo列表均无问题。

我刚下载了DEMO，确实有这个问题，就是在一个视频播放时候，再滑动一下它就会暂停，看了源码，是在 AutoPlayUtils 这个类中的 onScrollPlayVideo 方法回调，他会 player.startButton.performClick(); 直接点击播放按钮，所以会导致播放的会暂停，暂停的会开始播放，也就是1楼说的这个问题。

**Comment by nakisaren** [comment]
if (player.state != Jzvd.STATE_PLAYING) {
                                player.startButton.performClick();
                            }
加上这个判断就没问题了

**Comment by lipangit** [comment]
确实有这个问题  能提交个pr吗兄弟@nakisaren

**Comment by yilylong** [comment]
这类里面的positionInList为什么没有赋值却一直在使用？

**Comment by lipangit** [comment]
positionInList这个变量在setUp的时候赋值当前列表的index。  只在列表中有用
