### ISSUE TITLE
使用JZMediaExo内核实现静音不起作用

### ISSUE THREAD

**Issue by xiangzhenwang** [Jzvd/JZVideo#218]
**什么jzvd版本
7.4.2
**什么播放器内核
JZMediaExo
**demo是否有这个问题
是
**自己做了哪些修改
只能直接在JZMediaExo全部静音，JZMediaExo里面没有调用JZMediaInterface里面的setVolume方法
**如何操作复现
将demo中自动播放的内核换成JZMediaExo.class
holder.jzvdStd.setUp(Urls.videoUrls[0][1], "饺子摇摆", Jzvd.SCREEN_NORMAL, JZMediaExo.class);

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/92149975-525fe780-ee51-11ea-9c55-24f7845d817e.png)

你看demo中的JzvdStdVolumeAfterFullscreen和JzvdStdVolume用exoplayer内核有问题吗。
