### ISSUE TITLE
Activity横屏,全屏播放返回变成了竖屏

### ISSUE THREAD

**Issue by yilylong** [Jzvd/JZVideo#224]
**什么jzvd版本
7.4.2
**什么播放器内核
Activity本身设置成 landscape  点击全屏播放后 退出全屏后 Activity 变成了竖屏。看原码退出全屏默认设置成NORMAL_ORIENTATION了

**Comment by lipangit** [comment]
参考demo的orientation界面，设置全屏前和全屏后的屏幕方向
