### ISSUE TITLE
如何让视频或音频 在锁屏息屏后继续播放

### ISSUE THREAD

**Issue by TakeNotes2019** [Jzvd/JZVideo#226]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
不调用jzvd.releaseallvideos, 恢复的时候ontextureAvaliable时setTexture恢复画面。
