### ISSUE TITLE
jzvdContext内存泄露

### ISSUE THREAD

**Issue by SanYueSI** [Jzvd/JZVideo#227]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
这个问题很严重，也是一个系统问题，下个大版本准备用kt重构，希望能解决这个问题。
