### ISSUE TITLE
播放的视频如何设置不本地缓存

### ISSUE THREAD

**Issue by zhangzhiy** [Jzvd/JZVideo#228]
对于有问题的视频播放后，后台对视频处理修复好以后，播放过该视频的APP再次播放视频还是有问题，其他手机都可以正常播放，应该是缓存问题，所以可以设置不使用缓存吗，或者如何清理视频缓存。

**Comment by lipangit** [comment]
修改视频的url。或者找到播放内核里操作缓存的api。mediaplayer没有，EXO和ijk没细研究过
