### ISSUE TITLE
ViewPager2+Fragment，处于播放的时候ViewPager2不能上下滑动，与播放器手势冲突，其他状态却可以上下滑动，

### ISSUE THREAD

**Issue by LCJIAN** [Jzvd/JZVideo#229]
**什么jzvd版本
7.4.2
**什么播放器内核
原生
**相关log是什么

**demo是否有这个问题

**自己做了哪些修改
无
**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by LCJIAN** [comment]
搞成全屏了

**Comment by lipangit** [comment]
ok
