### ISSUE TITLE
自定义播放界面 点击全屏播放 界面会闪以下

### ISSUE THREAD

**Issue by owenxiao-AS** [Jzvd/JZVideo#232]
有谁遇到过吗  怎么解决啊

**Comment by lipangit** [comment]
需要更多信息，最好截图视频说明

**Comment by owenxiao-AS** [comment]
> 需要更多信息，最好截图视频说明

可以加个联系方式吗  弄好久了 还是不行

**Comment by lipangit** [comment]
加我微信



---原始邮件---
发件人: "owenxiao-AS"<notifications@github.com&gt;
发送时间: 2020年9月8日(周二) 下午3:38
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JZVideo] 自定义播放界面 点击全屏播放 界面会闪以下 (#232)




  
需要更多信息，最好截图视频说明
  
可以加个联系方式吗  弄好久了 还是不行

**Comment by wallyperry** [comment]
manifests里播放界面Activity添加：
`android:configChanges="orientation|screenSize|keyboardHidden"`
