### ISSUE TITLE
video paused when notifyDataSetChanged();

### ISSUE THREAD

**Issue by techpkm** [Jzvd/JZVideo#235]
I am using TikTok style from your demo but stuck in issue that when implement a button on UI of player as to like a video, when click on like button and and update the UI using notifyDataSetChanged();, video first pause, buffer then play. And if we use notifyItemChanged(), it simply pauses the video. However, I am using to play the video using autoPlayVideo with player.startVideoAfterPreloading();. Help me to keep video playing without pause on like button click.

**Comment by kHRYSTAL** [comment]
do not use `notifyItemChanged` or `notifyDataSetChanged` if RecyclerView has videoplayer item, because when `onBindViewHolder` will call `videoplayer#setUp`.
you can update item by ItemHolder with custom method,

eg.
```ItemHolder.java
class ItemHolder extends RecyclerView.ViewHolder {

    private boolean isFillPart;

    public ItemHolder(View itemView) {
        super(itemView);
        ...
    }

    public void setFillPart(boolean isFillPart) {
        this.isFillPart = isFillPart;
    }

    public void fill(VideoBean videoBean) {
        fillOther(videoBean);
        if (!isFillPart) {
            fillVideo(videoBean);
        }
    }
    
    private void fillOther(VideoBean otherBean) {
        ...
    }

    private void fillVideo(VideoBean videoBean) {
        ...
    }
}
```

and use custom method find ItemHolder to update itemView

```
 public void updateItem(VideoBean item) {
        if (item == null)
            return;

        long id = item.getId();
        int index = -1;
        // TODO find id of index;
        if (index >= 0) {
            RecyclerView.ViewHolder holder = getHolder(recyclerView, index);
            if (holder instanceof ItemHolder) {
                ((ItemHolder) holder).setFillPart(true); // 设置不更新attach
                ((ItemHolder) holder).fill(item);
                ((ItemHolder) holder).setFillPart(false); // 还原attach
            } else {
                adapter.notifyItemChanged(index);
            }
        }
    }

    public static RecyclerView.ViewHolder getHolder(RecyclerView recyclerView, int index) {
        if (null == recyclerView || null == recyclerView.getAdapter() || recyclerView.getAdapter().getItemCount() == 0)
            return null;
        int count = recyclerView.getAdapter().getItemCount();
        if (index < 0 || index > count -1) {
            return null;
        }
        RecyclerView.ViewHolder holder = recyclerView.findViewHolderForAdapterPosition(index);
        if (holder == null) {
            RecyclerView.RecycledViewPool pool = recyclerView.getRecycledViewPool();
            int type = 0; // default itemType if you has more itemType you can appoint
            holder = pool.getRecycledView(type);
            try {
                pool.putRecycledView(holder);
            } catch (Exception e) {

            }
        }
        return holder;
    }
```

and if you what to update item you can call `updateItem`

**Comment by techpkm** [comment]
This is my code and code above, with that I am not able implement with my code. Please help

public class TikTokFragment extends Fragment {
    View view;
    Context context;

    private RecyclerView rvTiktok;
    private HomeViewAdapter mAdapter;
    private ViewPagerLayoutManager mViewPagerLayoutManager;
    private int mCurrentPosition = -1;

    List<VideoData> dataList = new ArrayList<>();

    public TikTokFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_tik_tok, container, false);
        context = getContext();

        rvTiktok = view.findViewById(R.id.rv_tiktok);

        mAdapter = new HomeViewAdapter(context, dataList, new HomeViewAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(int position, VideoData item, View view) {
                switch (view.getId()) {
                    case R.id.img_like:
                        if (ConstVar.sharedPref.getBoolean(ConstVar.isLogin, false)) {
                            ToastMaker.getInstance(context).createToastMessage("Video ID: " + item.getId() + " Clicked", 0);
                            likeVideo(position, item);
                        } else {
                            ToastMaker.getInstance(context).createToastMessage("Please Login First", 1);
                        }
                        break;
                }
            }
        });
        mViewPagerLayoutManager = new ViewPagerLayoutManager(context, OrientationHelper.VERTICAL);
        rvTiktok.setLayoutManager(mViewPagerLayoutManager);
        rvTiktok.setAdapter(mAdapter);

        callForAllVideo();

        mViewPagerLayoutManager.setOnViewPagerListener(new OnViewPagerListener() {
            @Override
            public void onInitComplete() {
                autoPlayVideo(0);
            }

            @Override
            public void onPageRelease(boolean isNext, int position) {
                if (mCurrentPosition == position) {
                    Jzvd.releaseAllVideos();
                }
            }

            @Override
            public void onPageSelected(int position, boolean isBottom) {
                if (mCurrentPosition == position) {
                    return;
                }
                autoPlayVideo(position);
                mCurrentPosition = position;
            }
        });

        rvTiktok.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {

            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                Jzvd jzvd = view.findViewById(R.id.videoplayer);
                if (jzvd != null && Jzvd.CURRENT_JZVD != null && jzvd.jzDataSource != null &&
                        jzvd.jzDataSource.containsTheUrl(Jzvd.CURRENT_JZVD.jzDataSource.getCurrentUrl())) {
                    if (Jzvd.CURRENT_JZVD != null && Jzvd.CURRENT_JZVD.screen != Jzvd.SCREEN_FULLSCREEN) {
                        Jzvd.releaseAllVideos();
                    }
                }
            }
        });

        return view;
    }

    private void callForAllVideo() {
        String loginId = ConstVar.sharedPref.getString(ConstVar.u_id, "");
        ApiInterface apiInterface = ApiClient.getRetrofitClient().create(ApiInterface.class);
        Call<AllVideoResponse> responseCall = apiInterface.showAllVideos(loginId);
        responseCall.enqueue(new Callback<AllVideoResponse>() {
            @Override
            public void onResponse(Call<AllVideoResponse> call, Response<AllVideoResponse> response) {
                if (response.isSuccessful()) {
                    if (!response.body().isError()) {
                        dataList.addAll(response.body().getVideoData());
                        mAdapter.notifyDataSetChanged();
                        ToastMaker.getInstance(context).createToastMessage(response.body().getMessage(), 2);
                    } else {
                        ToastMaker.getInstance(context).createToastMessage(response.body().getMessage(), 1);
                    }
                }
            }

            @Override
            public void onFailure(Call<AllVideoResponse> call, Throwable t) {
                ToastMaker.getInstance(context).createToastMessage("ERROR CONNECTING SERVER", 2);
            }
        });
    }

    private void autoPlayVideo(int position) {
        if (rvTiktok == null || rvTiktok.getChildAt(0) == null) {
            return;
        }
        JzvdStdPlayer player = rvTiktok.getChildAt(0).findViewById(R.id.videoplayer);
        if (player != null) {
            player.startVideoAfterPreloading();
        }
    }

    @Override
    public void onPause() {
        super.onPause();
        Jzvd.releaseAllVideos();
    }

    private void likeVideo(final int position, final VideoData item) {
        String action = item.getLike_status();
        if (action.equals("1")) {
            action = "0";
            item.setLike_count(String.valueOf(Integer.parseInt(item.getLike_count()) - 1));

        } else {
            action = "1";
            item.setLike_count(String.valueOf(Integer.parseInt(item.getLike_count()) + 1));

        }
        dataList.remove(position);
        item.setLike_status(action);
        dataList.add(position, item);
        mAdapter.notifyDataSetChanged();
    }
}

**Comment by techpkm** [comment]
If you can implement the code in TikTokActivity demo, that will be better. Thanks

**Comment by techpkm** [comment]
> do not use `notifyItemChanged` or `notifyDataSetChanged` if RecyclerView has videoplayer item, because when `onBindViewHolder` will call `videoplayer#setUp`.
> you can update item by ItemHolder with custom method,
> 
> eg.
> 
> ```java
> class ItemHolder extends RecyclerView.ViewHolder {
> 
>     private boolean isFillPart;
> 
>     public ItemHolder(View itemView) {
>         super(itemView);
>         ...
>     }
> 
>     public void setFillPart(boolean isFillPart) {
>         this.isFillPart = isFillPart;
>     }
> 
>     public void fill(VideoBean videoBean) {
>         fillOther(videoBean);
>         if (!isFillPart) {
>             fillVideo(videoBean);
>         }
>     }
>     
>     private void fillOther(VideoBean otherBean) {
>         ...
>     }
> 
>     private void fillVideo(VideoBean videoBean) {
>         ...
>     }
> }
> ```
> 
> and use custom method find ItemHolder to update itemView
> 
> ```java
>  public void updateItem(VideoBean item) {
>         if (item == null)
>             return;
> 
>         long id = item.getId();
>         int index = -1;
>         // TODO find id of index;
>         if (index >= 0) {
>             RecyclerView.ViewHolder holder = getHolder(recyclerView, index);
>             if (holder instanceof ItemHolder) {
>                 ((ItemHolder) holder).setFillPart(true);
>                 ((ItemHolder) holder).fill(item);
>                 ((ItemHolder) holder).setFillPart(false); 
>             } else {
>                 adapter.notifyItemChanged(index);
>             }
>         }
>     }
> 
>     public static RecyclerView.ViewHolder getHolder(RecyclerView recyclerView, int index) {
>         if (null == recyclerView || null == recyclerView.getAdapter() || recyclerView.getAdapter().getItemCount() == 0)
>             return null;
>         int count = recyclerView.getAdapter().getItemCount();
>         if (index < 0 || index > count -1) {
>             return null;
>         }
>         RecyclerView.ViewHolder holder = recyclerView.findViewHolderForAdapterPosition(index);
>         if (holder == null) {
>             RecyclerView.RecycledViewPool pool = recyclerView.getRecycledViewPool();
>             int type = 0; // default itemType if you has more itemType you can appoint
>             holder = pool.getRecycledView(type);
>             try {
>                 pool.putRecycledView(holder);
>             } catch (Exception e) {
> 
>             }
>         }
>         return holder;
>     }
> ```
> 
> and if you what to update item you can call `updateItem`
> 
> in addition, you can store ItemHolder and position, when you want to update itemView you can getItemHolder by position to update childView

Requested to help soon on this

**Comment by techpkm** [comment]
I am unable to implement this code in my project. I request you to implement this code in demo TikTokActivity

**Comment by arsalrao** [comment]
@techpkm did you test or fix this issue? as I'm also facing the same issue.
