### ISSUE TITLE
抖音播放列表

### ISSUE THREAD

**Issue by huyanminggithub** [Jzvd/JZVideo#236]
版本7.4.2
双击列表时候 底下会出现控制条，但是单击时候不会出现应该是个BUG 没控制好显示
![图片](https://user-images.githubusercontent.com/20252039/93322172-9ab1d900-f845-11ea-884a-8d963620b4ae.png)

**Comment by lipangit** [comment]
是个问题，感谢你的反馈



---原始邮件---
发件人: "huyanminggithub"<notifications@github.com&gt;
发送时间: 2020年9月16日(周三) 下午5:54
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 抖音播放列表 (#236)




 
版本7.4.2
 双击列表时候 底下会出现控制条，但是单击时候不会出现应该是个BUG 没控制好显示
