### ISSUE TITLE
选择倍速播放出错

### ISSUE THREAD

**Issue by AmoyJJ** [Jzvd/JZVideo#237]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:7.4.1
**什么播放器内核
默认内核
**相关log是什么
1 android.media.MediaPlayer.setPlaybackParams(Native Method)
2 cn.jzvd.JZMediaSystem.setSpeed(JZMediaSystem.java:132)

**Comment by lipangit** [comment]
犹未可知，保持关注



---原始邮件---
发件人: "AmoyJJ"<notifications@github.com&gt;
发送时间: 2020年9月17日(周四) 上午10:35
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 选择倍速播放出错 (#237)




 
**什么jzvd版本
 cn.jzvd:jiaozivideoplayer:7.4.1
 **什么播放器内核
 默认内核
 **相关log是什么
 1&nbsp;android.media.MediaPlayer.setPlaybackParams(Native Method)
 2&nbsp;cn.jzvd.JZMediaSystem.setSpeed(JZMediaSystem.java:132)
