### ISSUE TITLE
在流中静音播放的时候，如何不打断后台音乐的播放

### ISSUE THREAD

**Issue by gaojunhuiBS** [Jzvd/JZVideo#240]
**需求描述
在流中静音播放视频时，会打断后台播放的音乐，如何实现，静音播放时，不中断后台正在播放的音乐。
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
在开始播放时会发出一个广播，打断音乐播放，继承jzvdstd复写开始播放函数(名字忘记了)，把父类的代码抄过来，去掉这个广播



---原始邮件---
发件人: "gaojunhuiBS"<notifications@github.com&gt;
发送时间: 2020年9月22日(周二) 下午5:56
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 在流中静音播放的时候，如何不打断后台音乐的播放 (#240)




 
**需求描述
 在流中静音播放视频时，会打断后台播放的音乐，如何实现，静音播放时，不中断后台正在播放的音乐。
 **其他app是否实现
 
**截图或者小视频说明
