### ISSUE TITLE
How to change the seek sensitivity?

### ISSUE THREAD

**Issue by dheerajbred** [Jzvd/JZVideo#241]
How to reduce the seek sensitivity? 
The sensitivity is too high. Small seeks resulting in minutes changes.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/94293191-8467f380-ff90-11ea-9bf2-311442655595.png)

jzvd int funcition touchActionMove(), this line control the sensitivity.  I will think about how to change the sensitivity.

**Comment by dheerajbred** [comment]
Got it. Thanks :)
