### ISSUE TITLE
视频全屏状态下点击重播按钮BUG

### ISSUE THREAD

**Issue by jinlinupup** [Jzvd/JZVideo#244]
**什么jzvd版本
demo 版本

**什么播放器内核
demo

**相关log是什么

**demo是否有这个问题
有

**自己做了哪些修改
无

**如何操作复现

demo中  自定义-播放完成不退出全屏状态-全屏状态下播放完成点击重播

**什么安卓版本，什么机型

**截图或者视频说明情况
上述操作后loading和封面背景图没有隐藏，视频内容没有显示，但是有声音

**Comment by lipangit** [comment]
这是个bug感谢你的反馈，研究一下



---原始邮件---
发件人: "jinlinupup"<notifications@github.com&gt;
发送时间: 2020年9月27日(周日) 中午11:32
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 视频全屏状态下点击重播按钮BUG (#244)




 
**什么jzvd版本
 demo 版本
 
**什么播放器内核
 demo
 
**相关log是什么
 
**demo是否有这个问题
 有
 
**自己做了哪些修改
 无
 
**如何操作复现
 
demo中  自定义-播放完成不退出全屏状态-全屏状态下播放完成点击重播
 
**什么安卓版本，什么机型
 
**截图或者视频说明情况
 上述操作后loading和封面背景图没有隐藏，视频内容没有显示，但是有声音
