### ISSUE TITLE
如何在Service中播放

### ISSUE THREAD

**Issue by yilylong** [Jzvd/JZVideo#245]
**需求描述
如果想要在Service中全局（后台）播放怎么实现比较好？现在jzplayer里面需要引用Activity 直接在Service里面初始化jzvd是行不通的. 如果从外面把jzvd传入Service 那就一直持有某个Activity 这样应该会导致activity一直无法被回收（内存泄漏）吧。难道只能使用MediaPlayer来播放？

**Comment by lipangit** [comment]
后台播放的步骤逻辑是什么样。或者有没有现成的 上线的app参考&nbsp; &nbsp;我下载看看&nbsp;



---原始邮件---
发件人: "hailongzhao"<notifications@github.com&gt;
发送时间: 2020年9月28日(周一) 下午2:45
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 如何在Service中播放 (#245)




 
**需求描述
 如果想要在Service中全局（后台）播放怎么实现比较好？现在jzplayer里面需要引用Activity 直接在Service里面初始化jzvd是行不通的. 如果从外面把jzvd传入Service 那就一直持有某个Activity 这样应该会导致activity一直无法被回收（内存泄漏）吧。难道只能使用MediaPlayer来播放？

**Comment by yilylong** [comment]
现在都页面播放嘛，如果实现音乐播放器的后台播放效果的话 就要在service里面播放嘛。以前做个类似的都是用mediaplay在service里面播放

**Comment by lipangit** [comment]
如果不需要ui就用mediaplayer，不需要用饺子



---原始邮件---
发件人: "hailongzhao"<notifications@github.com&gt;
发送时间: 2020年9月28日(周一) 下午5:43
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JZVideo] 如何在Service中播放 (#245)




 
现在都页面播放嘛，如果实现音乐播放器的后台播放效果的话 就要在service里面播放嘛。以前做个类似的都是用mediaplay在service里面播放

**Comment by yilylong** [comment]
主要是想着 饺子 已经封装了很多方法 用起来方便 mediaplayer要自己去写一遍。实际上现在用饺子不调用releasepalyer的话退出界面也是一直在播放的，（可以将播放器存到Application里面实现全局控制播放）但是在锁屏后无法继续播了，后来发现是锁屏后不会回调TextureView的onSurfaceTextureAvailable导致不播放。自己定义播放器修改了下，可以在锁屏后持续持续播放。但是还是感觉没有比在service实现优雅。

**Comment by lipangit** [comment]
有现成的上线的app吗  我研究一下是否有必要

**Comment by rockerkekex** [comment]
> 主要是想着 饺子 已经封装了很多方法 用起来方便 mediaplayer要自己去写一遍。实际上现在用饺子不调用releasepalyer的话退出界面也是一直在播放的，（可以将播放器存到Application里面实现全局控制播放）但是在锁屏后无法继续播了，后来发现是锁屏后不会回调TextureView的onSurfaceTextureAvailable导致不播放。自己定义播放器修改了下，可以在锁屏后持续持续播放。但是还是感觉没有比在service实现优雅。

请问是如何修改的呢，现在也碰到了这个问题
