### ISSUE TITLE
在 CollapsingToolbarLayout中 使用 jzvd 导致 toolbar 里面的 title 无法根据 view 的展开折叠状态来控制显示 or 隐藏

### ISSUE THREAD

**Issue by CodeSaid** [Jzvd/JZVideo#248]
**什么jzvd版本:7.4.2

**什么播放器内核:默认

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

xml代码如下：
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/coordinator_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:titleEnabled="false">

            <LinearLayout
                android:id="@+id/ll_video"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:background="#000"
                app:layout_collapseMode="parallax">

               <cn.jzvd.JzvdStd
                    android:id="@+id/jzvd_video"
                    android:layout_width="match_parent"
                    android:visibility="gone"
                    android:layout_height="300dp" />

                <androidx.appcompat.widget.AppCompatImageView
                    android:id="@+id/imageView"
                    android:layout_width="match_parent"
                    android:layout_height="300dp"
                    android:scaleType="centerCrop"
                    android:src="@mipmap/test" />

            </LinearLayout>

            <View
                android:layout_width="match_parent"
                android:layout_height="40dp"
                android:background="@drawable/gradient"
                android:fitsSystemWindows="true" />

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?actionBarSize"
                app:layout_collapseMode="pin">

                <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <androidx.appcompat.widget.AppCompatImageView
                        android:id="@+id/iv_back"
                        android:layout_width="23dp"
                        android:layout_height="32dp"
                        android:layout_centerVertical="true"
                        android:padding="5dp"
                        android:src="@mipmap/icon_back_white" />

                    <TextView
                        android:id="@+id/title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_centerInParent="true"
                        android:layout_gravity="center"
                        android:text="186****1145刚刚下载了"
                        android:textColor="@color/white"
                        android:textSize="13sp" />

                    <androidx.appcompat.widget.AppCompatImageView
                        android:id="@+id/iv_gift_center"
                        android:layout_width="28dp"
                        android:layout_height="26dp"
                        android:layout_alignParentRight="true"
                        android:layout_centerVertical="true"
                        android:layout_marginRight="10dp"
                        android:padding="5dp"
                        android:src="@mipmap/icon_gift" />

                </RelativeLayout>
            </androidx.appcompat.widget.Toolbar>
        </com.google.android.material.appbar.CollapsingToolbarLayout>

        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabLayout"
            android:layout_width="match_parent"
            android:layout_height="?actionBarSize"
            android:background="#2196F3" />
    </com.google.android.material.appbar.AppBarLayout>

    <androidx.viewpager.widget.ViewPager
        android:id="@+id/viewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />
</androidx.coordinatorlayout.widget.CoordinatorLayout>

Activity中改变 Toolbar里面的 TextView显示隐藏代码如下：
 if (0 == verticalOffset) {
                    if (state != CollapsingToolbarLayoutState.EXPANDED) {
                        state = CollapsingToolbarLayoutState.EXPANDED;//修改状态标记为展开
                        title.setVisibility(View.INVISIBLE);
                    }
                } else if (Math.abs(verticalOffset) >= appBarLayout.getTotalScrollRange()) {
                    if (state != CollapsingToolbarLayoutState.COLLAPSED) {
                        title.setVisibility(View.VISIBLE);//隐藏播放按钮
                        state = CollapsingToolbarLayoutState.COLLAPSED;//修改状态标记为折叠
                    }
                } else {
                    if (state != CollapsingToolbarLayoutState.INTERNEDIATE) {
                        if (state == CollapsingToolbarLayoutState.COLLAPSED) {
                            title.setVisibility(View.INVISIBLE);//由折叠变为中间状态时隐藏播放按钮
                        }

                        state = CollapsingToolbarLayoutState.INTERNEDIATE;//修改状态标记为中间
                    }
                }

Toolbar的背景颜色可以正常改变，但是 里面 view 改不了显示 or 隐藏，如果去除掉 JzvdStd 这个 view 就能正常控制，我不知道是不是因为 视频播放控件的问题？

**Comment by lipangit** [comment]
单就textview而言此时该如何判断显示隐藏



---原始邮件---
发件人: "CodeSaid"<notifications@github.com&gt;
发送时间: 2020年9月30日(周三) 中午11:04
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 在 CollapsingToolbarLayout中 使用 jzvd 导致 toolbar 里面的 title 无法根据 view 的展开折叠状态来控制显示 or 隐藏 (#248)




 
**什么jzvd版本:7.4.2
 
**什么播放器内核:默认
 
**相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 
**如何操作复现
 
**什么安卓版本，什么机型
 
**截图或者视频说明情况
 
xml代码如下：
 
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
 xmlns:app="http://schemas.android.com/apk/res-auto"
 android:id="@+id/coordinator_layout"
 android:layout_width="match_parent"
 android:layout_height="match_parent"&gt;
 <com.google.android.material.appbar.AppBarLayout     android:id="@+id/app_bar"     android:layout_width="match_parent"     android:layout_height="wrap_content"&gt;     <com.google.android.material.appbar.CollapsingToolbarLayout         android:layout_width="match_parent"         android:layout_height="wrap_content"         app:layout_scrollFlags="scroll|exitUntilCollapsed"         app:titleEnabled="false"&gt;         <LinearLayout             android:id="@+id/ll_video"             android:layout_width="match_parent"             android:layout_height="wrap_content"             android:orientation="vertical"             android:background="#000"             app:layout_collapseMode="parallax"&gt;            <cn.jzvd.JzvdStd                 android:id="@+id/jzvd_video"                 android:layout_width="match_parent"                 android:visibility="gone"                 android:layout_height="300dp" /&gt;             <androidx.appcompat.widget.AppCompatImageView                 android:id="@+id/imageView"                 android:layout_width="match_parent"                 android:layout_height="300dp"                 android:scaleType="centerCrop"                 android:src="@mipmap/test" /&gt;         </LinearLayout&gt;         <View             android:layout_width="match_parent"             android:layout_height="40dp"             android:background="@drawable/gradient"             android:fitsSystemWindows="true" /&gt;         <androidx.appcompat.widget.Toolbar             android:id="@+id/toolbar"             android:layout_width="match_parent"             android:layout_height="?actionBarSize"             app:layout_collapseMode="pin"&gt;             <RelativeLayout                 android:layout_width="match_parent"                 android:layout_height="match_parent"&gt;                 <androidx.appcompat.widget.AppCompatImageView                     android:id="@+id/iv_back"                     android:layout_width="23dp"                     android:layout_height="32dp"                     android:layout_centerVertical="true"                     android:padding="5dp"                     android:src="@mipmap/icon_back_white" /&gt;                 <TextView                     android:id="@+id/title"                     android:layout_width="wrap_content"                     android:layout_height="wrap_content"                     android:layout_centerInParent="true"                     android:layout_gravity="center"                     android:text="186****1145刚刚下载了"                     android:textColor="@color/white"                     android:textSize="13sp" /&gt;                 <androidx.appcompat.widget.AppCompatImageView                     android:id="@+id/iv_gift_center"                     android:layout_width="28dp"                     android:layout_height="26dp"                     android:layout_alignParentRight="true"                     android:layout_centerVertical="true"                     android:layout_marginRight="10dp"                     android:padding="5dp"                     android:src="@mipmap/icon_gift" /&gt;             </RelativeLayout&gt;         </androidx.appcompat.widget.Toolbar&gt;     </com.google.android.material.appbar.CollapsingToolbarLayout&gt;     <com.google.android.material.tabs.TabLayout         android:id="@+id/tabLayout"         android:layout_width="match_parent"         android:layout_height="?actionBarSize"         android:background="#2196F3" /&gt; </com.google.android.material.appbar.AppBarLayout&gt; <androidx.viewpager.widget.ViewPager     android:id="@+id/viewPager"     android:layout_width="match_parent"     android:layout_height="match_parent"     app:layout_behavior="@string/appbar_scrolling_view_behavior" /&gt;  
</androidx.coordinatorlayout.widget.CoordinatorLayout&gt;
 
Activity中改变 Toolbar里面的 TextView显示隐藏代码如下：
 if (0 == verticalOffset) {
 if (state != CollapsingToolbarLayoutState.EXPANDED) {
 state = CollapsingToolbarLayoutState.EXPANDED;//修改状态标记为展开
 title.setVisibility(View.INVISIBLE);
 }
 } else if (Math.abs(verticalOffset) &gt;= appBarLayout.getTotalScrollRange()) {
 if (state != CollapsingToolbarLayoutState.COLLAPSED) {
 title.setVisibility(View.VISIBLE);//隐藏播放按钮
 state = CollapsingToolbarLayoutState.COLLAPSED;//修改状态标记为折叠
 }
 } else {
 if (state != CollapsingToolbarLayoutState.INTERNEDIATE) {
 if (state == CollapsingToolbarLayoutState.COLLAPSED) {
 title.setVisibility(View.INVISIBLE);//由折叠变为中间状态时隐藏播放按钮
 }
                     state = CollapsingToolbarLayoutState.INTERNEDIATE;//修改状态标记为中间                 }             }  
Toolbar的背景颜色可以正常改变，但是 里面 view 改不了显示 or 隐藏，如果去除掉 JzvdStd 这个 view 就能正常控制，我不知道是不是因为 视频播放控件的问题？

**Comment by CodeSaid** [comment]
希望能根据 CollapsingToolbarLayout 的展开 or 折叠状态控制显示隐藏

**Comment by lipangit** [comment]
通过什么代码判断&nbsp; &nbsp;你研究一下&nbsp; 然后我看看怎么把它放到库里



---原始邮件---
发件人: "CodeSaid"<notifications@github.com&gt;
发送时间: 2020年10月2日(周五) 中午11:55
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JZVideo] 在 CollapsingToolbarLayout中 使用 jzvd 导致 toolbar 里面的 title 无法根据 view 的展开折叠状态来控制显示 or 隐藏 (#248)




 
希望能根据 CollapsingToolbarLayout 的展开 or 折叠状态控制显示隐藏

**Comment by CodeSaid** [comment]
我试了好多都无法判断显示隐藏，才来问问你的
