### ISSUE TITLE
可以设置循环播放吗？

### ISSUE THREAD

**Issue by LankyBin-lb** [Jzvd/JZVideo#249]
**需求描述
播放一个视频，播放结束之后无缝回到该视频开头继续播放

**其他app是否实现
原生videoview可以在complete的监听里设置start

**Comment by lipangit** [comment]
jzdatasource.looping=true



---原始邮件---
发件人: "LankyBin"<notifications@github.com&gt;
发送时间: 2020年9月30日(周三) 中午11:23
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 可以设置循环播放吗？ (#249)




 
**需求描述
 播放一个视频，播放结束之后无缝回到该视频开头继续播放
 
**其他app是否实现
 原生videoview可以在complete的监听里设置start
