### ISSUE TITLE
斗鱼的hls貌似无法播放

### ISSUE THREAD

**Issue by whp98** [Jzvd/JZVideo#25]
**需求描述
真实链接
http://tx2play1.douyucdn.cn/live/263824rvckg2QDjU.flv?uuid=
![image](https://user-images.githubusercontent.com/32877126/71304599-2bb56a00-2404-11ea-851f-b1315767a38b.png)
手机上就是显示加载的小圈不停加载
播放页面情况
![image](https://user-images.githubusercontent.com/32877126/71304619-628b8000-2404-11ea-8944-8f96c8ed9a32.png)
其他格式h264可以播放

**其他app是否实现
暂时没试过
**截图或者小视频说明
H264可以播放
![image](https://user-images.githubusercontent.com/32877126/71304699-f9583c80-2404-11ea-9d5c-5bd8132030fe.png)
播放页面
![image](https://user-images.githubusercontent.com/32877126/71304714-2b699e80-2405-11ea-9f1d-cac52d1273da.png)

**Comment by lipangit** [comment]
能不能播取决于播放内核，咱们项目是做ui的，超出老臣解决范围。一行代码切换到其他播放内核试试，demo 有切换的例子。

**Comment by whp98** [comment]
OK
