### ISSUE TITLE
请问如何预先加载好一些视频缓存

### ISSUE THREAD

**Issue by huanghaoming** [Jzvd/JZVideo#250]
我想在base application里就先将几个视频缓存到本地，然后当每次Jzvd播放的时候可以起到快速播放的效果，请问可以实现吗

**Comment by lipangit** [comment]
暂无方法&nbsp; 没听说这么做的



---原始邮件---
发件人: "Borsalino"<notifications@github.com&gt;
发送时间: 2020年10月8日(周四) 晚上8:07
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 请问如何预先加载好一些视频缓存 (#250)




 
我想在base application里就先将几个视频缓存到本地，然后当每次Jzvd播放的时候可以起到快速播放的效果，请问可以实现吗
