### ISSUE TITLE
左右滑动控制进度条建议

### ISSUE THREAD

**Issue by xaEHu** [Jzvd/JZVideo#252]
**需求描述
左右滑动调节进度太过于灵敏了，小小的拖动，进度条调节框显示就已经拖动了4分多钟了，有可以设置灵敏度阈值的方法吗？

**Comment by lipangit** [comment]
这个记得以前有朋友改过，ontouch里面有一刚计算拖动的距离的。这个要改影响体验



---原始邮件---
发件人: "侠一胡"<notifications@github.com&gt;
发送时间: 2020年10月13日(周二) 晚上9:56
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 左右滑动控制进度条建议 (#252)




 
**需求描述
 左右滑动调节进度太过于灵敏了，小小的拖动，进度条调节框显示就已经拖动了4分多钟了，有可以设置灵敏度阈值的方法吗？

**Comment by xaEHu** [comment]
可是小小的拖动就几分钟体验更糟啊😂你说的有改过的有没有历史记录？

**Comment by xaEHu** [comment]
我宁愿拖动到手机最右侧才快进十多秒也不希望是几分钟

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/96034708-85f05180-0e94-11eb-8856-797e28ca6230.png)

代码在这里，需要在这个公式里面添加一个变量，控制灵敏度。

我清楚的记得这个问题有个网友改过了，我还测过了，加了一个变量，jzvd.变量 = [0-1]   可以设置灵敏度 怎么没了。。[捂脸]

**Comment by wanggaolin** [comment]
这个进度条怎么禁用拖拽啊？不是禁用触摸事件？

**Comment by xaEHu** [comment]
我是这么做：
`@Override
    public boolean onTouch(View v, MotionEvent event) {
        if (v.getId() == R.id.surface_container) {
            if(event.getAction() == MotionEvent.ACTION_UP && mChangePosition){
                //拖动进度条不做处理
                return true;
            }
        }
        return super.onTouch(v, event);
    }

    @Override
    public void showProgressDialog(float deltaX, String seekTime, long seekTimePosition, String totalTime, long totalTimeDuration) {
        //不显示进度框
    }`

**Comment by xaEHu** [comment]
> 这个进度条怎么禁用拖拽啊？不是禁用触摸事件？
我是这么做：
` @Override
    public boolean onTouch(View v, MotionEvent event) {
        if (v.getId() == R.id.surface_container) {
            if(event.getAction() == MotionEvent.ACTION_UP && mChangePosition){
                //直播没有进度条，拖动进度可能导致异常
                return true;
            }
        }
        return super.onTouch(v, event);
    }`

`@Override
public void showProgressDialog(float deltaX, String seekTime, long seekTimePosition, String totalTime, long totalTimeDuration) {
    //不显示进度框
}`

**Comment by wanggaolin** [comment]
我这里获取到的mChangePosition一直是false，不知道为什么

**Comment by wanggaolin** [comment]
在全屏的情况下才管用，非全屏获取到的mChangePosition一直是false

**Comment by xaEHu** [comment]
ok了，视频长度/屏幕宽度=2000+，我把这个值修改为固定值80，达到我想要的效果了。

**Comment by lipangit** [comment]
好的兄弟  能提交一个pr吗  弄一个变量让用户可以设置灵敏度

**Comment by ZhuSky** [comment]
![image](https://user-images.githubusercontent.com/18596232/107905759-6e33f180-6f8a-11eb-87f7-1c0655636ec4.png)
我补充一下修改后的代码😂
