### ISSUE TITLE
增加锁定屏幕的代码之后双击暂停的功能失效了

### ISSUE THREAD

**Issue by xaEHu** [Jzvd/JZVideo#253]
**什么jzvd版本
7.5.0
**自己做了哪些修改
把demo里面的锁定屏幕代码copy过来
**如何操作复现
双击屏幕，不会暂停
**什么安卓版本，什么机型
Android 10 ，redmi k20pro
**截图或者视频说明情况

**Comment by wanggaolin** [comment]
你这个解决了吗

**Comment by xaEHu** [comment]
> 你这个解决了吗

解决了，不用demo里面那个。直接简单粗暴：

```
 @Override
    public void onClickUiToggle() {
        if(isLock){
            return;
        }
        super.onClickUiToggle();
    }

    @Override
    public boolean onTouch(View v, MotionEvent event) {
        if(isLock){
            return true;
        }
        return super.onTouch(v,event);
    }
```

**Comment by wanggaolin** [comment]
直接禁用onTouch就可以，但是对应的暂停功能也没有了，这个不行啊

**Comment by xaEHu** [comment]
> 直接禁用onTouch就可以，但是对应的暂停功能也没有了，这个不行啊

锁定屏幕就是要把所有按键屏蔽包括暂停键啊

**Comment by xaEHu** [comment]
> 直接禁用onTouch就可以，但是对应的暂停功能也没有了，这个不行啊

你可以考虑自己定义一个暂停按钮和锁屏按钮一起，在判断到isLock里面做显示

**Comment by wanggaolin** [comment]
我知道，我只想禁用拖拽事件，里面有一个onStopTrackingTouch方法，注释掉之后不能拖拽，但是只能拖拽一次还是不行。
这个有办法吗

**Comment by ToxicR** [comment]
> 我知道，我只想禁用拖拽事件，里面有一个onStopTrackingTouch方法，注释掉之后不能拖拽，但是只能拖拽一次还是不行。
> 这个有办法吗

如果你只是想在锁屏的时候禁用拖拽事件，那可以自己增加一个锁屏的状态，在点击之后禁止相关控件进行拖拽就行了

**Comment by wanggaolin** [comment]
好的，谢谢，同问一个我想在视频上面新增一个返回按钮，触屏显示，反之隐藏，这个要怎么自定义?
