### ISSUE TITLE
进度条如何禁止拖拽

### ISSUE THREAD

**Issue by wanggaolin** [Jzvd/JZVideo#254]
**什么jzvd版本
7.0.5

**什么播放器内核
ijkplayer

**什么安卓版本，什么机型
小米8

**Comment by lipangit** [comment]
继承jzvdstd 在各个播放状态中控制进度条



---原始邮件---
发件人: "mark"<notifications@github.com&gt;
发送时间: 2020年10月15日(周四) 下午2:07
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 进度条如何禁止拖拽 (#254)




 
**什么jzvd版本
 7.0.5
 
**什么播放器内核
 ijkplayer
 
**什么安卓版本，什么机型
 小米8

**Comment by wanggaolin** [comment]
还是不明白，在哪个方法下面控制呢

**Comment by wanggaolin** [comment]
继承哪一个方法？
