### ISSUE TITLE
竖屏全屏状态下布局穿透问题

### ISSUE THREAD

**Issue by MixRabbit** [Jzvd/JZVideo#256]

**Comment by MixRabbit** [comment]
在列表中使用播放器全屏播放，全屏为竖屏的全屏，视频画面下的空白区域布局穿透了

**Comment by MixRabbit** [comment]
![Uploading Snipaste_2020-10-19_18-12-45.png…]()

**Comment by lipangit** [comment]
图片没上来

**Comment by MixRabbit** [comment]
![Snipaste_2020-10-19_18-12-45](https://user-images.githubusercontent.com/26106846/96529380-9307a900-12b7-11eb-9e38-2259373c9863.png)

**Comment by MixRabbit** [comment]
app首页是四个fragment模块+底部button，第一个模块中的fragment是tab+子fragment，视频列表是在子fragment中，并且使用旧版本以及迁移到androidx之后的最新版本都是有这种情况

**Comment by lipangit** [comment]
demo是否有这问题

**Comment by MixRabbit** [comment]
demo上没有发现该问题，后续我在demo中写一个列表再测试一下

**Comment by Lingzh0ng** [comment]
全屏状态下背景偶尔会变透明
