### ISSUE TITLE
如何自适应高度？

### ISSUE THREAD

**Issue by slimboy2008** [Jzvd/JZVideo#257]
不指定播放器的具体高度，如何自适应高度？

**Comment by slimboy2008** [comment]
在未播放显示视频封面图的情况下（有横屏和竖屏的视频），不指定固定的播放器高度，封面图会拉伸，如何自适应高度？

**Comment by slimboy2008** [comment]
已解决。

**Comment by lipangit** [comment]
怎么解决的

**Comment by hhbuct** [comment]
同问，如何解决的 @slimboy2008

**Comment by nemo-ex** [comment]
@slimboy2008 解决了分享出来别跑啊

**Comment by p132241** [comment]
> @slimboy2008 解决了分享出来别跑啊



> 同问，如何解决的 @slimboy2008



> 怎么解决的

设置一个父控件LinearLayout包裹jzvdstd 高为wrap_parent  jzvdstd的高设置为match_parent  然后java设置视频缩图的时候封面图大小和视频大小一样就可以了
