### ISSUE TITLE
作者您好，关于播放器实现无限循环播放的问题

### ISSUE THREAD

**Issue by 1173859245** [Jzvd/JZVideo#258]
您好，我下载了您的demo，里面并没有看到循环播放的接口。现在我的项目是要求播放很短的一个本地视频实现无限循环播放。网上文档说是    复写 onStateAutoComplete方法，
 @Override
    public void onStateAutoComplete() {
        super.onStateAutoComplete();
        startVideo();
    }
但是此方法最多两遍就会出现异常。我这边切换的EXO 内核本地视频也会播放不了。求解决思路和方法。

**Comment by 1173859245** [comment]
sry, 找到了。应该是复写父类的 onCompletion() 方法，我的方法错了。汗。。。

**Comment by lipangit** [comment]
demo有写   jzdatasource.looping=true 就无线循环了
