### ISSUE TITLE
请问支持rtsp吗

### ISSUE THREAD

**Issue by a454436646** [Jzvd/JZVideo#260]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by wanggaolin** [comment]
视频播放上下有黑边，如何自适应屏幕大小？

**Comment by lipangit** [comment]
视频格式取决于播放内核。一行代码切换播放内核 试试其他

**Comment by lipangit** [comment]
@wanggaolin 参考demo首页的视频填充方式
