### ISSUE TITLE
我有个问题请教一下，重力感应怎么关闭啊？

### ISSUE THREAD

**Issue by zjiamin** [Jzvd/JZVideo#262]
我屏蔽了所有autoFullScreen相关代码，只留下了全屏按钮的事件后，还是会重力感应切换全屏。
因为我遇到了重力感应只有第一次打开管用，点击全屏按钮切换一次全屏以后，重力感应就无效了。

**Comment by zjiamin** [comment]
sorry，明白了,在清单文件activity标签里screenOrientation=“nosensor”可以关，播放器里的代码是监听设备重力传感的

**Comment by lipangit** [comment]
ok
