### ISSUE TITLE
引入库报错！

### ISSUE THREAD

**Issue by MaleWxt** [Jzvd/JZVideo#263]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by MaleWxt** [comment]
[](url)
![Uploading image.png…]()

**Comment by MaleWxt** [comment]
![1603964208(1)](https://user-images.githubusercontent.com/18377645/97551006-61a48100-1a0d-11eb-846f-efe42006a8a7.jpg)

**Comment by Liberations** [comment]
需要更多信息。

**Comment by liuheqing** [comment]
我的也是 从7.4.1 更新到 7.6.0 就报错这个，提示：error processing C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.4.21\4a668382d7c38688d3490afde93b6a113ed46698\kotlin-stdlib-1.4.21.jar

**Comment by liuheqing** [comment]
而且我想知道有隐藏进度条的方法么？

**Comment by chenkexu** [comment]
我引入最新版7.7.0' 之后，提示kotlin插件需要更新
