### ISSUE TITLE
播放失败之后，触屏touch显示信息丢失

### ISSUE THREAD

**Issue by wanggaolin** [Jzvd/JZVideo#264]
因为网络原因或者其他原因失败之后，触屏touch之后，视频标题和返回ICON图片都不显示了，这个怎么修复?

**Comment by lipangit** [comment]
demo有这问题吗  如何复现  截图看看

**Comment by wanggaolin** [comment]
如图，点击屏幕，touch之后视频title和icon都不显示了
![Uploading 1234.jpg…]()

**Comment by wanggaolin** [comment]
如图，点击屏幕，touch之后视频title和icon都不显示了
![error](https://user-images.githubusercontent.com/12725872/97650595-03bb7c00-1a95-11eb-995f-2acbf94ea0ac.jpg)

**Comment by wanggaolin** [comment]
![error](https://user-images.githubusercontent.com/12725872/97650676-3bc2bf00-1a95-11eb-9c1a-c8c90382b263.jpg)

**Comment by lipangit** [comment]
继承jzvdstd复写onerror函数 取得error状态 把你要的icon显示出来
