### ISSUE TITLE
如何全屏播放9:16的视频

### ISSUE THREAD

**Issue by aa41336160** [Jzvd/JZVideo#265]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by aa41336160** [comment]
全屏播放时，16:9的全屏才能铺满，9:16 的视频 两边都是黑的， 如何让9:16的视频也铺满呢

**Comment by lipangit** [comment]
demo首页有铺满屏幕的例子
