### ISSUE TITLE
如何隐藏TextureView中间的播放按钮!!!

### ISSUE THREAD

**Issue by Licarey** [Jzvd/JZVideo#266]
你好，如何隐藏TextureView中间的播放按钮?

**Comment by lipangit** [comment]
继承jzvdstd复写各个状态的函数，分别在各个状态中修改隐藏与否



---原始邮件---
发件人: "carey"<notifications@github.com&gt;
发送时间: 2020年11月2日(周一) 晚上8:15
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 如何隐藏TextureView中间的播放按钮!!! (#266)




 
你好，如何隐藏TextureView中间的播放按钮?

**Comment by Licarey** [comment]
@lipangit 谢谢 问题解决了，麻烦问题，7.0.5属于稳定版本么，我这边只是用了单纯的竖屏播放视频
