### ISSUE TITLE
cn.jzvd:jiaozivideoplayer:7.4.2版本,如何实现用户埋点的统计?

### ISSUE THREAD

**Issue by Yangwenhua44** [Jzvd/JZVideo#267]
文档介绍说 创建一个类 MyUserActionStd implements JZUserActionStd,但是JZUserActionStd这个类根本找不到,是换了方式,?还是类改了名字,现在怎么实现这个功能?

**Comment by Yangwenhua44** [comment]
已在旧版本中找到解决方案

**Comment by lipangit** [comment]
继承jzvdstd复写相应函数取得相应事件进行埋点
