### ISSUE TITLE
Exo 播放视频变形,IJK 没问题

### ISSUE THREAD

**Issue by CleverSJX** [Jzvd/JZVideo#268]
## 什么jzvd版本

```
implementation 'cn.jzvd:jiaozivideoplayer:7.5.0'
```
## 什么播放器内核
JZMediaExo

## 什么安卓版本，什么机型

- 小米盒子3 Android 5.1

- 小米盒子3S Android 6.0 

## 截图或者视频说明情况
视频是1080*1920的, 被压扁了 没有保持原来比例,  但是IJK正常,但是我需要EXO来播放
![5fab5a7ac4b3f_5fab5a7b4351c](https://user-images.githubusercontent.com/26036692/98761861-4e33e580-2411-11eb-8f43-38ded817e4b8.jpg)

**Comment by Liberations** [comment]
SimpleExoPlayer setVideoScalingMode试试
