### ISSUE TITLE
Set Height and Width programatically Standard Player Reycycleview 

### ISSUE THREAD

**Issue by dev990** [Jzvd/JZVideo#270]
I have a json of list of video with different height and width but ,  i dont need fixed height of Standard player . how to solve this issues .

**Comment by lipangit** [comment]
Extends jzvdstd override onvideosize() function to stop fix height and weight by mediaplayer. 

Is that you WANT?

**Comment by dev990** [comment]
> Extends jzvdstd override onvideosize() function to stop fix height and weight by mediaplayer.
> 
> Is that you WANT?

There is no method onvideosize() .   only onVideoSizeChanged() is avalaible.
