### ISSUE TITLE
获取播放的进度

### ISSUE THREAD

**Issue by lamandys** [Jzvd/JZVideo#272]
**需求描述
连个获取播放进度的api都没有？

**其他app是否实现

**截图或者小视频说明

**Comment by Howard-2015** [comment]
这个问题我也发现了，看代码发现进度条竟然是一个时间的计时器，每300秒回去一次进度，这个接口回调 public abstract long getCurrentPosition();为什么这样设计呢？

**Comment by Liberations** [comment]
onProgress中可以监听到
