### ISSUE TITLE
RecyclerView.addOnChildAttachStateChangeListener with Fragment is not working.

### ISSUE THREAD

**Issue by 969rishi** [Jzvd/JZVideo#274]
I in my app there is bottom navigation when I setup this JZVideo in one of tab of bottom navigation. Fragment with recyclerview working but when I implemented **addOnChildAttachStateChangeListener** for **onChildViewAttachedToWindow** and **onChildViewDetachedFromWindow** listeners not working. But with simple Activity everything is working fine. Please help me with any workaround for this problem.

**Comment by Liberations** [comment]
recyclerView.addOnScrollListener work well?
