### ISSUE TITLE
播放本地视频一直处于loading当中

### ISSUE THREAD

**Issue by ygl750994280** [Jzvd/JZVideo#277]

**Comment by xaEHu** [comment]
检查路径

**Comment by gaohequan** [comment]
应该你是安卓10吧

**Comment by gaohequan** [comment]
解决了么

**Comment by ygl750994280** [comment]
> 解决了么
华为手机  安卓10    我用这个在A activity能正常使用  同样的代码放在B Activity就不行了  A activity应为需求原因是一个banner所以我把这个视频控件封装到了banner控件里面  再把banner控件放在B使用   就能播放了
