### ISSUE TITLE
viewPager中,全屏会崩溃

### ISSUE THREAD

**Issue by QiaoYang0923** [Jzvd/JZVideo#279]
**什么jzvd版本
7.5.0

**什么播放器内核
默认

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

在商品详情activity中,顶部有个banner,第一页显示视频,,播放正常,点击全屏就崩溃,清单文件也配置了 android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"

**Comment by Liberations** [comment]
log
