### ISSUE TITLE
饺子视频，仿抖音界面，为啥没有自动播放啊，跟它demo 写的一样，滑动能自动播放。

### ISSUE THREAD

**Issue by Newwaygo** [Jzvd/JZVideo#284]
饺子视频，仿抖音界面，为啥没有自动播放啊，跟它demo 写的一样，滑动能自动播放。
  // 饺子视频播放器。
    implementation 'cn.jzvd:jiaozivideoplayer:7.5.0'

**Comment by hjja1** [comment]
在ViewPagerListener  的onInitComplete里有没有加上 autoPlayVideo(0);
