### ISSUE TITLE
网速没问题，每次点击播放，都要加载几秒钟，1-4s吧，1秒很少，为啥啊

### ISSUE THREAD

**Issue by wangzizhong** [Jzvd/JZVideo#287]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by buhanzhe** [comment]
是不是没做缓存？ 每次都要重新下载呀。可以加缓存试试

**Comment by yangqb** [comment]
请问你找到原因了吗

**Comment by Liberations** [comment]
可以尝试用cdn缓存
