### ISSUE TITLE
demo 中 高度自定义的AGVIDEO有几个BUG，我可以帮忙改下么？

### ISSUE THREAD

**Issue by buhanzhe** [Jzvd/JZVideo#288]
**什么jzvd版本 最新的

**什么播放器内核 demo中是exo 我用的原生的

**相关log是什么

**demo是否有这个问题 有

**自己做了哪些修改 切换视频的时候，我清理了下视频，然后再加载新的视频

**如何操作复现 点击下一级按钮，有时候界面会卡死。

**什么安卓版本，什么机型 android Q redmi K30 pro

**截图或者视频说明情况

**Comment by Liberations** [comment]
欢迎PR

**Comment by buhanzhe** [comment]
@Liberations 怎么pr
