### ISSUE TITLE
无法播放RTSP

### ISSUE THREAD

**Issue by ArroWen2904** [Jzvd/JZVideo#293]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:7.5.0

**什么播放器内核
使用文档QuickStart的方式，或是使用JZMediaIjk、JZMediaIjk、JZMediaSystem都无法播放

**相关log是什么

**demo是否有这个问题
若更改为RTSP的播放连结则有问题

**自己做了哪些修改
若更改为RTSP的播放连结
ex:rtsp://XXXXXXX:8554/STREAM

**如何操作复现
可于PC端建立一个rtsp server，视频使用H-265编解码

**什么安卓版本，什么机型
samsung A71

**截图或者视频说明情况
一直loading 画面出不来

**Comment by lipangit** [comment]
取决于播放内核，超出本裤能力范围。
