### ISSUE TITLE
全屏问题

### ISSUE THREAD

**Issue by jiyeon-dino** [Jzvd/JZVideo#294]
**什么jzvd版本
7.4.1
**什么播放器内核
默认的

JzvdStd在界面上方，视频下方是一个scrollview,点击全屏按钮整个界面先横屏显示了，视频没有全屏，再点击全屏按钮视频才全屏。

**Comment by lipangit** [comment]
需要更多信息，做了哪些修改，demo有没有类似场景。

“JzvdStd在界面上方，视频下方是一个scrollview ”这场景可以放到demo中，新建个activity单独展示。
