### ISSUE TITLE
引入库竟然是apk包增加了100M

### ISSUE THREAD

**Issue by xybCoder** [Jzvd/JZVideo#295]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
Jz基础只有100k。其他的按需添加



---原始邮件---
发件人: "闯码头"<notifications@github.com&gt;
发送时间: 2020年12月22日(周二) 晚上6:35
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 引入库竟然是apk包增加了100M (#295)




 
**需求描述
 
**其他app是否实现
 
**截图或者小视频说明
