### ISSUE TITLE
Exoplayer播放视频封面图到开始播放中间会闪黑屏,不平滑

### ISSUE THREAD

**Issue by CleverSJX** [Jzvd/JZVideo#296]
##需求描述
Exoplayer播放视频封面图到开始播放中间会闪黑屏,不平滑

##其他app是否实现
实现

**截图或者小视频说明

**Comment by lipangit** [comment]
demo中exo和阿里云的情况比较明显。

**Comment by lipangit** [comment]
原理是这样，如果以mediaplayer start的回调作为开始播放的标志，隐藏缩略图，那么缩略图隐藏了，图像还没出来，闪黑屏是这么来的，那么需要以开始渲染图像为开始播放的标志。

![image](https://user-images.githubusercontent.com/2038071/103077598-0e187300-460b-11eb-9810-3f53d3821980.png)

研究一下这些播放内核开始渲染图像的回调是哪个，让jzvd进入onStatePlaying状态即可。

**Comment by nemo-ex** [comment]
自定义JzvdStd，覆盖这个方法
```
override fun changeUIToPreparingPlaying() {
    super.changeUIToPreparingPlaying()
    posterImageView.visibility = View.VISIBLE // 优化播放前隐藏封面导致黑屏闪一下
}
````
