### ISSUE TITLE
如何在播放视频时，切换成其他视频

### ISSUE THREAD

**Issue by robinhoo2010** [Jzvd/JZVideo#36]
**需求描述
当前实现自动循环播放，当服务器发送更新指令后，使用新的列表播放，使用新的列表播放时，第一次会一直显示加载，貌似等第一个视频播放完（界面上没有视频）的时间后，第二个视频才能显示，这时加载消失

**截图或者小视频说明

**Comment by lipangit** [comment]
1.服务器怎么发送的什么指令。

2.两次播放互不相关，调用jzvd.releaseAllvideos()，即可播放下一个视频。
