### ISSUE TITLE
Go to the end of a video for a live

### ISSUE THREAD

**Issue by jewom** [Jzvd/JZVideo#42]
Hi and thanks for your amazing work!

I'm looking to play a stream video.
It's working but using `startVideo() `the player play the begining of the stream and I would like to play the end of the video to be in the live time.
How can I do that ?

**Comment by lipangit** [comment]
Does  it work?

mediaInterface.seekTo(position);

**Comment by jewom** [comment]
I have only seekToManualPosition() and seekToInAdvance() with the videoPlayer

**Comment by jewom** [comment]
Ok I tried :

videoPlayer.mediaInterface.seekTo()

but I have this error :

    java.lang.IllegalStateException: videoPlayer.mediaInterface must not be null

**Comment by lipangit** [comment]
call this function must it is playing
