### ISSUE TITLE
./gradlew build 时显示“程序包android.support.annotation不存在”

### ISSUE THREAD

**Issue by lipangit** [Jzvd/JZVideo#43]
**什么jzvd版本
7.2.0最新版本
**相关log是什么
![image](https://user-images.githubusercontent.com/2038071/72998548-f9e75700-3e38-11ea-8484-b4dd53813bdd.png)

**demo是否有这个问题
有
**如何操作复现

**什么安卓版本，什么机型

**最好有截图或者视频说明情况

**Comment by cuibg** [comment]
应该是兼容Androidx了吧

**Comment by lipangit** [comment]
以前没有androidx的时候就这样，不知道怎么解决



---原始邮件---
发件人: "CuiBenguang"<notifications@github.com&gt;
发送时间: 2020年3月14日(周六) 上午10:20
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Nathen"<1066666651@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] ./gradlew build 时显示“程序包android.support.annotation不存在” (#43)




 
应该是兼容Androidx了吧
