### ISSUE TITLE
RecyclerView中全屏返回后不能继续播放问题

### ISSUE THREAD

**Issue by Tell-me502** [Jzvd/JZVideo#45]
RecyclerView添加划出屏幕释放JZ 后，RecyclerView中的视频全屏播放返回也会释放掉JZ.
Z.
添加的代码：
rv_featured_video.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
                Log.e("initFeatureVideo", "setFeaturedVideo: 事件监听，可见播放");
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer jzVideoPlayer = view.findViewById(R.id.jz_video);
                if (jzVideoPlayer != null && JZVideoPlayer.CURRENT_JZVD != null &&
                        jzVideoPlayer.jzDataSource.containsTheUrl(JZVideoPlayer.CURRENT_JZVD.jzDataSource.getCurrentUrl())) {
                    if (JZVideoPlayer.CURRENT_JZVD != null && JZVideoPlayer.CURRENT_JZVD.screen != JZVideoPlayer.SCREEN_FULLSCREEN) {
                        Log.e("initFeatureVideo", "setFeaturedVideo: 事件监听，不可见停止播放"+JZVideoPlayer.CURRENT_JZVD.screen );
                        JZVideoPlayer.releaseAllVideos();
                        //JZVideoPlayer.goOnPlayOnPause();
                        //Jzvd.releaseAllVideos();
                    }
                }
            }
        });
全屏返回后不能继续播放问题

**Comment by lipangit** [comment]
demo有这个问题吗，你的需求demo中有吗
