### ISSUE TITLE
有办法监听由于网络原因导致的视频卡顿吗，或者获得卡顿次数

### ISSUE THREAD

**Issue by dk568382923** [Jzvd/JZVideo#58]
经过测试：当网络不佳视频中断直到恢复网络视频继续播放onStatePause、onStatePreparing、onStatePlaying、onStateError均没有调用

**Comment by lipangit** [comment]
查一下哪个播放内核支持这种回调，我还真不清楚



---原始邮件---
发件人: "dk568382923"<notifications@github.com&gt;
发送时间: 2020年2月27日(周四) 下午2:51
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 有办法监听由于网络原因导致的视频卡顿吗，或者获得卡顿次数 (#58)



经过测试：当网络不佳视频中断直到恢复网络视频继续播放onStatePause、onStatePreparing、onStatePlaying、onStateError均没有调用
