### ISSUE TITLE
播放期间出现错误能否自动尝试继续播放呢？

### ISSUE THREAD

**Issue by xuzh2018** [Jzvd/JZVideo#59]
**需求描述
播放器有时候会播放期间播放错误或者画面静止，这时候能自动重新尝试播放吗？而不是手动点击播放失败按钮
**其他app是否实现
是
**截图或者小视频说明

**Comment by lipangit** [comment]
继承jzvdstd&nbsp; 复写onerror函数，一error就播放video



---原始邮件---
发件人: "xuzh2018"<notifications@github.com&gt;
发送时间: 2020年2月27日(周四) 下午3:44
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 播放期间出现错误能否自动尝试继续播放呢？ (#59)



**需求描述
 播放器有时候会播放期间播放错误或者画面静止，这时候能自动重新尝试播放吗？而不是手动点击播放失败按钮
 **其他app是否实现
 是
 **截图或者小视频说明

**Comment by pspms51920** [comment]
error就播放video， 请问下 是重新开始，还是接着继续播放啊

**Comment by lipangit** [comment]
重播



---原始邮件---
发件人: "pspms51920"<notifications@github.com&gt;
发送时间: 2020年3月12日(周四) 中午12:26
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 播放期间出现错误能否自动尝试继续播放呢？ (#59)




 
error就播放video， 请问下 是重新开始，还是接着继续播放啊

**Comment by pspms51920** [comment]
有没有办法继续播放啊， 比如保存进度，然后再次播放后，seekto 进度位置

**Comment by lipangit** [comment]
这个问题其实有点复杂，在onerror之后没法从播放内核取得进度，那么你就得每隔比如0.5秒取得一次进度，在onerror之后使用这个进度



---原始邮件---
发件人: "pspms51920"<notifications@github.com&gt;
发送时间: 2020年3月12日(周四) 中午12:47
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 播放期间出现错误能否自动尝试继续播放呢？ (#59)




 
有没有办法继续播放啊， 比如保存进度，然后再次播放后，seekto 进度位置
