### ISSUE TITLE
文档都没有正式的吗?都是未完待续或者简单2句话,不知所云...

### ISSUE THREAD

**Issue by zxyaust** [Jzvd/JZVideo#62]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by zxyaust** [comment]
还是不用为妙

**Comment by lipangit** [comment]
请先下载demo，过一遍demo的所有按钮看看有没有你的需求。


哪句话不知所云，我给你分析一下



---原始邮件---
发件人: "张小勇"<notifications@github.com&gt;
发送时间: 2020年3月1日(周日) 凌晨3:04
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 文档都没有正式的吗?都是未完待续或者简单2句话,不知所云... (#62)



**需求描述
 
**其他app是否实现
 
**截图或者小视频说明

**Comment by lipangit** [comment]
咖啡之翼女老板尹峰，几年前在非你莫属节目中说：不可能让所有人都同意你的观点，这是一种奢望，也不可能通过简单的沟通让所有人都理解你的观点(这句是我加的)。人就是矛盾的载体，在矛盾中寻找平衡。


对了，将来饺子币能买的时候记得买点，肯定不亏钱。
https://github.com/Jzvd/JZT



祝好。



---原始邮件---
发件人: "张小勇"<notifications@github.com&gt;
发送时间: 2020年3月1日(周日) 凌晨3:06
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 文档都没有正式的吗?都是未完待续或者简单2句话,不知所云... (#62)



还是不用为妙
