### ISSUE TITLE
如何保存recyclerview里的视频播放进度位置

### ISSUE THREAD

**Issue by huanghaoming** [Jzvd/JZVideo#65]
有一个recyclerview，我想实现滑动自动播放的功能，这个在网上实现方式很多。。。然后我遇到一个问题，那就是，先点击第一个视频，然后往下滑动，第一个视频会暂停。。再往上滑，第一个视频被回收掉了。。。我希望第一个视频能够继续播放。。。。请问这个地方怎么实现呢

**Comment by lipangit** [comment]
实现逻辑是，在列表的item回收时不释放mediaplayer，item重新出现的时候继续播放。
看似不难，但是项目的现有结构做不到，需要深入修改。也很难。



---原始邮件---
发件人: "huanghaoming"<notifications@github.com&gt;
发送时间: 2020年3月6日(周五) 中午11:32
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 如何保存recyclerview里的视频播放进度位置 (#65)



有一个recyclerview，我想实现滑动自动播放的功能，这个在网上实现方式很多。。。然后我遇到一个问题，那就是，先点击第一个视频，然后往下滑动，第一个视频会暂停。。再往上滑，第一个视频被回收掉了。。。我希望第一个视频能够继续播放。。。。请问这个地方怎么实现呢
