### ISSUE TITLE
竖屏的页面设置全屏无效

### ISSUE THREAD

**Issue by hongsiping** [Jzvd/JZVideo#80]
**什么jzvd版本
7.2.0
**相关log是什么

**demo是否有这个问题

**自己做了哪些修改
复写gotoScreenFullscreen方法加了宽高判断，宽大于高设置横屏Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE
**如何操作复现
页面竖屏，全屏置横屏情况  会复现
**什么安卓版本，什么机型
三星S8
**截图或者视频说明情况

**Comment by lipangit** [comment]
研究demo的orientationActivity。
