### ISSUE TITLE
点击全屏时问题

### ISSUE THREAD

**Issue by JLuani** [Jzvd/JZVideo#81]
点击全屏时整个app先横屏，视频没有全屏还得重新点了才有播放。在横屏点了全屏视频就可以全屏退出后app就恢复竖屏了

**Comment by lipangit** [comment]
demo有这问题吗，需要更多信息。

**Comment by JLuani** [comment]
> demo有这问题吗，需要更多信息。
全屏问题已经解决了。但是全屏后退出全屏recycleview就只剩视频，其他控件都不见了，请问是怎么回事

**Comment by JLuani** [comment]
全屏问题已经解决了。但是全屏后退出全屏recycleview就只剩视频，其他控件都不见了，请问是怎么回事

**Comment by lipangit** [comment]
jzvdstd外包裹layout



---原始邮件---
发件人: "JLuani"<notifications@github.com&gt;
发送时间: 2020年3月23日(周一) 上午10:17
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 点击全屏时问题 (#81)




  
demo有这问题吗，需要更多信息。
 全屏问题已经解决了。但是全屏后退出全屏recycleview就只剩视频，其他控件都不见了，请问是怎么回事

**Comment by SusuperOsaiyan** [comment]
> 全屏问题已经解决了。但是全屏后退出全屏recycleview就只剩视频，其他控件都不见了，请问是怎么回事

请问全屏问题是怎么解决的

**Comment by Liberations** [comment]
参考demo
