### ISSUE TITLE
拉流时候出现loading不消失的情况

### ISSUE THREAD

**Issue by RiceRichhonour** [Jzvd/JZVideo#86]
**最新版本

拉流，我目前测试了百度的RTMP直播流，**正常播放**时候，经常会出现loading不消失的问题

**demo也有这个问题

**多次打开重新加载，或者切换出app，再切回来播放即可重现。

提供rtmp流一个供参考
"rtmp://cyberplayerplay.kaywang.cn/cyberplayer/demo201711-L1"

**多个手机都会出现
![QQ图片20200327150805](https://user-images.githubusercontent.com/26269539/77731007-ff316f80-703c-11ea-9cfd-02b676bee467.png)

**Comment by RiceRichhonour** [comment]
多次测试后，发现不光是这个loading不消失，视频点击也不会出现隐藏的进度条和标题栏，不知道什么原因

**Comment by lipangit** [comment]
用其他播放内核尝试，ijk&nbsp; exo&nbsp; 一行代码切换播放内核，setup的最后一个参数。



---原始邮件---
发件人: "mizhou"<notifications@github.com&gt;
发送时间: 2020年3月27日(周五) 下午3:10
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86)




 
**最新版本
 
拉流，我目前测试了百度的RTMP直播流，正常播放时候，经常会出现loading不消失的问题
 
**demo也有这个问题
 
**多次打开重新加载，或者切换出app，再切回来播放即可重现。
 
提供rtmp流一个供参考
 "rtmp://cyberplayerplay.kaywang.cn/cyberplayer/demo201711-L1"
 
**多个手机都会出现

**Comment by RiceRichhonour** [comment]
> 用其他播放内核尝试，ijk&nbsp; exo&nbsp; 一行代码切换播放内核，setup的最后一个参数。
> […](#)
> ---原始邮件--- 发件人: "mizhou"<notifications@github.com&gt; 发送时间: 2020年3月27日(周五) 下午3:10 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86) **最新版本 拉流，我目前测试了百度的RTMP直播流，正常播放时候，经常会出现loading不消失的问题 **demo也有这个问题 **多次打开重新加载，或者切换出app，再切回来播放即可重现。 提供rtmp流一个供参考 "rtmp://cyberplayerplay.kaywang.cn/cyberplayer/demo201711-L1" **多个手机都会出现 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

拉直播流只能用ijk内核播放吧，我指定的是ijk的内核

**Comment by RiceRichhonour** [comment]
> 用其他播放内核尝试，ijk&nbsp; exo&nbsp; 一行代码切换播放内核，setup的最后一个参数。
> […](#)
> ---原始邮件--- 发件人: "mizhou"<notifications@github.com&gt; 发送时间: 2020年3月27日(周五) 下午3:10 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86) **最新版本 拉流，我目前测试了百度的RTMP直播流，正常播放时候，经常会出现loading不消失的问题 **demo也有这个问题 **多次打开重新加载，或者切换出app，再切回来播放即可重现。 提供rtmp流一个供参考 "rtmp://cyberplayerplay.kaywang.cn/cyberplayer/demo201711-L1" **多个手机都会出现 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢大佬的回复，希望大佬不忙的时候看一下，我感觉是监听有问题呢，有时候播放正常了，各种监听都失效了，点击屏幕没反应，上面的下面的都不会显示和隐藏了。

**Comment by lipangit** [comment]
你研究一下播放内核是否有这个事件的通知，然后饺子是否漏掉这个事件。
如果漏掉了我给他加上，如果内核取得不到这个事件我也没办法。



---原始邮件---
发件人: "mizhou"<notifications@github.com&gt;
发送时间: 2020年3月27日(周五) 下午5:33
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86)




  
用其他播放内核尝试，ijk&nbsp; exo&nbsp; 一行代码切换播放内核，setup的最后一个参数。
 …
 ---原始邮件--- 发件人: "mizhou"<notifications@github.com&gt; 发送时间: 2020年3月27日(周五) 下午3:10 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86) **最新版本 拉流，我目前测试了百度的RTMP直播流，正常播放时候，经常会出现loading不消失的问题 **demo也有这个问题 **多次打开重新加载，或者切换出app，再切回来播放即可重现。 提供rtmp流一个供参考 "rtmp://cyberplayerplay.kaywang.cn/cyberplayer/demo201711-L1" **多个手机都会出现 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
感谢大佬的回复，希望大佬不忙的时候看一下，我感觉是监听有问题呢，有时候播放正常了，各种监听都失效了，点击屏幕没反应，上面的下面的都不会显示和隐藏了。

**Comment by hzwplus** [comment]
> > 用其他播放内核尝试，ijk  exo  一行代码切换播放内核，setup的最后一个参数。
> > […](#)
> > ---原始邮件--- 发件人: "mizhou"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年3月27日(周五) 下午3:10 收件人: "Jzvd/JiaoZiVideoPlayer"<[JiaoZiVideoPlayer@noreply.github.com](mailto:JiaoZiVideoPlayer@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86) **最新版本 拉流，我目前测试了百度的RTMP直播流，正常播放时候，经常会出现loading不消失的问题 **demo也有这个问题 **多次打开重新加载，或者切换出app，再切回来播放即可重现。 提供rtmp流一个供参考 "rtmp://cyberplayerplay.kaywang.cn/cyberplayer/demo201711-L1" **多个手机都会出现 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 感谢大佬的回复，希望大佬不忙的时候看一下，我感觉是监听有问题呢，有时候播放正常了，各种监听都失效了，点击屏幕没反应，上面的下面的都不会显示和隐藏了。

我也遇到了这个情况

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/78420662-ab013d80-7683-11ea-9fc3-320d104e4618.png)

亲测，报这个错误，超出本库解决范围。

**Comment by xushanning** [comment]
同遇到这个问题

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/79968026-2c4d3280-84c2-11ea-801d-b6e5687e6879.png)

应该没走这里

**Comment by xushanning** [comment]
> ![image](https://user-images.githubusercontent.com/2038071/79968026-2c4d3280-84c2-11ea-801d-b6e5687e6879.png)
> 
> 应该没走这里

这个是ijkplayer问题还是框架的bug？

**Comment by RiceRichhonour** [comment]
> > ![image](https://user-images.githubusercontent.com/2038071/79968026-2c4d3280-84c2-11ea-801d-b6e5687e6879.png)
> > 应该没走这里
> 
> 这个是ijkplayer问题还是框架的bug？

框架问题

**Comment by lipangit** [comment]
视频开始播放的标志是开始渲染图像，否则在开始视频的时候会有卡顿，这是框架的判断。

如果个别url不走这个过程，可以不走渲染的判断，只走基础的start。

**Comment by lipangit** [comment]
修改框架可以解决这个问题



---原始邮件---
发件人: "xushanning"<notifications@github.com&gt;
发送时间: 2020年4月22日(周三) 晚上6:21
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86)




  

 
应该没走这里
  
这个是ijkplayer问题还是框架的bug？

**Comment by fredfuly** [comment]
> 修改框架可以解决这个问题
> […](#)
> ---原始邮件--- 发件人: "xushanning"<notifications@github.com&gt; 发送时间: 2020年4月22日(周三) 晚上6:21 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86) 应该没走这里 这个是ijkplayer问题还是框架的bug？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，我也遇到了相同的问题，请问如何修改框架才能解决这个问题？

**Comment by tristanyi** [comment]
> 修改框架可以解决这个问题
> […](#)
> ---原始邮件--- 发件人: "xushanning"<notifications@github.com&gt; 发送时间: 2020年4月22日(周三) 晚上6:21 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 拉流时候出现loading不消失的情况 (#86) 应该没走这里 这个是ijkplayer问题还是框架的bug？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

同样遇到了这个问题，播放器的状态监听有没有对外接口可以使用，有的话可以手动关闭loading组件

**Comment by ZhuSky** [comment]
同求问，还是遇到这个问题了。各位大佬是怎么解决的 ，求给小弟支个招🙏

**Comment by RiceRichhonour** [comment]
> 同求问，还是遇到这个问题了。各位大佬是怎么解决的 ，求给小弟支个招

我换成了gsy那个框架

**Comment by ZhuSky** [comment]
我就是从那个框架 换过来的。。。。

**Comment by RiceRichhonour** [comment]
> 我就是从那个框架 换过来的。。。。

==换回去呗，那个蛮好用的

**Comment by ZhuSky** [comment]
忘记是因为啥了，但是确实是有个原因 才换的

**Comment by ZhuSky** [comment]
这个作者是不维护了么？这么长时间了，这个问题还在呢

**Comment by RiceRichhonour** [comment]
> 这个作者是不维护了么？这么长时间了，这个问题还在呢

作者回复，亲测，报这个错误，超出本库解决范围。

**Comment by ZhuSky** [comment]
哎。。。 不知道为啥 exo内核就不行，换用ali 的就没问题了，很蛋疼

**Comment by ZhuSky** [comment]
我ca，老兄 我搞定了，主动去重写改变一下播放的状态就行了
![image](https://user-images.githubusercontent.com/18596232/132439545-1cfcf983-9a2e-41a2-b891-ce0fe310b103.png)

**Comment by RiceRichhonour** [comment]
> 我ca，老兄 我搞定了，主动去重写改变一下播放的状态就行了
> ![image](https://user-images.githubusercontent.com/18596232/132439545-1cfcf983-9a2e-41a2-b891-ce0fe310b103.png)

woc，我用的是ijk，因为我是拉流，你这是正常播放内容吗

**Comment by ZhuSky** [comment]
我的是正常的播放内容
'''
http://ottvideohwyun.hifuntv.com/internettv/c1/2021/04/15/5F9CC4475539D01D0391E757D7D37F64.ts?pm=6aF00PRMseRZ8shgg7E5AndUrUqJ46vXWtuA4i7DD8t7UQthDArjlz0ZXi3HXbT1q7IffR8VOW1KVfy9YZt7oqaXun2tsb6MmevxiyAKTwWIlROg63cYdQlhXubstxKBf1frQ0A57szYMQQyyS8bObeFsuS~B8QUdrmdKn5UD9mX9cQhLl9Ln9dasp0vYuTY9pPCeCnE3pSEcnNJF0VXrjIMUGUdSyFxBJG~Vd7WeFQ3pJK1IW3uqbw0aTqaPb8jQTAyiPCu1kNM4qsj2e3cluHS~~RNIh_VMFayQEro3YBG_tvHGuCFb_BDGfJJRmOzfJfBOA6igEkOMNgcGPbTxAVPHfKSwzG9PtmV_1C_7LAN70UYU6YVAAylHoo2pEe7~URGwEg2bbFKdZh4oaujbTA~S7g-&cpno=6r25po&ruid=8db70831229b42b7&_t=005
'''

**Comment by RiceRichhonour** [comment]
> 我的是正常的播放内容
> '''
> http://ottvideohwyun.hifuntv.com/internettv/c1/2021/04/15/5F9CC4475539D01D0391E757D7D37F64.ts?pm=6aF00PRMseRZ8shgg7E5AndUrUqJ46vXWtuA4i7DD8t7UQthDArjlz0ZXi3HXbT1q7IffR8VOW1KVfy9YZt7oqaXun2tsb6MmevxiyAKTwWIlROg63cYdQlhXubstxKBf1frQ0A57szYMQQyyS8bObeFsuS~B8QUdrmdKn5UD9mX9cQhLl9Ln9dasp0vYuTY9pPCeCnE3pSEcnNJF0VXrjIMUGUdSyFxBJG~Vd7WeFQ3pJK1IW3uqbw0aTqaPb8jQTAyiPCu1kNM4qsj2e3cluHS~~RNIh_VMFayQEro3YBG_tvHGuCFb_BDGfJJRmOzfJfBOA6igEkOMNgcGPbTxAVPHfKSwzG9PtmV_1C_7LAN70UYU6YVAAylHoo2pEe7~URGwEg2bbFKdZh4oaujbTA~S7g-&cpno=6r25po&ruid=8db70831229b42b7&_t=005
> '''

好吧，这个的话作者回复了，换个内核

**Comment by ZhuSky** [comment]
😂

**Comment by ZhuSky** [comment]
@RiceRichhonour  这个小问题太多了，我也有点想换了
