### ISSUE TITLE
跳转指定播放

### ISSUE THREAD

**Issue by zouyan532** [Jzvd/JZVideo#87]
版本7后的如何设置到指定位置播放

**Comment by lipangit** [comment]
apiactivity 有例子，demo中搜索seektoinadvance&nbsp; 亲测有效



---原始邮件---
发件人: "zouyan532"<notifications@github.com&gt;
发送时间: 2020年3月27日(周五) 下午4:55
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 跳转指定播放 (#87)




 
版本7后的如何设置到指定位置播放

**Comment by zouyan532** [comment]
你好，没有在最新demo中搜到这个跳转的关键词，接口有一个seekTo的方法，使用但是无效

**Comment by 565151501** [comment]
seektoinadvance 设置了无效  seekto也无效

**Comment by lipangit** [comment]
这个功能亲测有效啊，你本地什么情况做了什么修改能详细说说吗



---原始邮件---
发件人: "snoopy"<notifications@github.com&gt;
发送时间: 2020年4月14日(周二) 晚上8:52
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 跳转指定播放 (#87)




 
seektoinadvance 设置了无效  seekto也无效

**Comment by 565151501** [comment]
首先谢谢作者答疑，经过再次尝试 需要设置  先        Jzvd.SAVE_PROGRESS=true;
 seektoinadvance才会生效

**Comment by lipangit** [comment]
是吗&nbsp; 这是bug&nbsp; 我去看看，感谢你的反馈



---原始邮件---
发件人: "snoopy"<notifications@github.com&gt;
发送时间: 2020年4月27日(周一) 下午5:29
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 跳转指定播放 (#87)




 
首先谢谢作者答疑，经过再次尝试 需要设置  先        Jzvd.SAVE_PROGRESS=true;
 seektoinadvance才会生效

**Comment by ssyRo156** [comment]
要明白 mPlayer.mediaInterface.seekTo(毫秒);
