### ISSUE TITLE
调用ChangeUrl函数修改url和title，title不会变

### ISSUE THREAD

**Issue by xaEHu** [Jzvd/JZVideo#93]
**什么jzvd版本
7.2.3

**如何操作复现
mPlayer.changeUrl(new JZDataSource(currentUrl,title),0);

文档说有三个changUrl函数，实际调用只有一个函数：
changeUrl(JZDataSource jzDataSource, long seekToInAdvance)。所以我就这样用，是我写错了吗？url能加载到正确的，但是title却是旧的的

**Comment by lipangit** [comment]
什么情况



---原始邮件---
发件人: "侠一胡"<notifications@github.com&gt;
发送时间: 2020年4月4日(周六) 下午5:47
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] Change U人类、 (#93)




 
**什么jzvd版本
 
**相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 
**如何操作复现
 
**什么安卓版本，什么机型
 
**截图或者视频说明情况

**Comment by xaEHu** [comment]
**什么jzvd版本
7.2.3

**如何操作复现
mPlayer.changeUrl(new JZDataSource(currentUrl,title),0);

文档说有三个changUrl函数，实际调用只有一个函数：
changeUrl(JZDataSource jzDataSource, long seekToInAdvance)。所以我就这样用，是我写错了吗？url能加载到正确的，但是title却是旧的的

**Comment by Liberations** [comment]
fixed https://github.com/Jzvd/JiaoZiVideoPlayer/commit/ae824cd75eaac7e44d99a61ec9ff3602e44fce72
