### ISSUE TITLE
执行到releaseAllVideos()闪退

### ISSUE THREAD

**Issue by xaEHu** [Jzvd/JZVideo#94]
**什么jzvd版本
7.2.3

**如何操作复现
给播放器设置m3u8的播放链接，然后loading转圈的时候点击关闭界面退出，会去执行到releaseAllVideos()就会导致崩溃

**Comment by xaEHu** [comment]
demo中的AGVideo也是一直在转圈，点击返回就会闪退。Android10，机型redmi k20pro

**Comment by AmoyJJ** [comment]
感觉是通病。不只是releaseAllVideos  
只要在转圈的时候触发释放资源都会崩溃
goOnPlayOnPause 也一样

**Comment by lipangit** [comment]
log什么样

**Comment by AmoyJJ** [comment]
1 android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1499)
2 android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1605)
3 android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:678)
4 cn.jzvd.JzvdStd.unregisterWifiListener(JzvdStd.java:888)
5 cn.jzvd.JzvdStd.reset(JzvdStd.java:832)
6 cn.jzvd.Jzvd.setCurrentJzvd(Jzvd.java:1035)
7 cn.jzvd.Jzvd.startVideo(Jzvd.java:568)
8 cn.jzvd.JzvdStd.startVideo(JzvdStd.java:185)
9 cn.jzvd.Jzvd.goOnPlayOnResume(Jzvd.java:961)
10 com.platform.education.module.practice.training.background.BackgroundFragment$onActivityCreated$2.onChildViewAttachedToWindow(BackgroundFragment.kt:66)

**Comment by lipangit** [comment]
这个一直是个坑



---原始邮件---
发件人: "AmoyJJ"<notifications@github.com&gt;
发送时间: 2020年4月21日(周二) 上午9:12
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 执行到releaseAllVideos()闪退 (#94)




 
1&nbsp;android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1499)
 2&nbsp;android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1605)
 3&nbsp;android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:678)
 4&nbsp;cn.jzvd.JzvdStd.unregisterWifiListener(JzvdStd.java:888)
 5&nbsp;cn.jzvd.JzvdStd.reset(JzvdStd.java:832)
 6&nbsp;cn.jzvd.Jzvd.setCurrentJzvd(Jzvd.java:1035)
 7&nbsp;cn.jzvd.Jzvd.startVideo(Jzvd.java:568)
 8&nbsp;cn.jzvd.JzvdStd.startVideo(JzvdStd.java:185)
 9&nbsp;cn.jzvd.Jzvd.goOnPlayOnResume(Jzvd.java:961)
 10&nbsp;com.platform.education.module.practice.training.background.BackgroundFragment$onActivityCreated$2.onChildViewAttachedToWindow(BackgroundFragment.kt:66)

**Comment by AmoyJJ** [comment]
大神找个时间填一填呀~话说切换播放内核的代码要放在那里application么。原生与EXO内核对视频的预加载速度有差别嘛

**Comment by AmoyJJ** [comment]
加载视频中还未播放时。触发了 goOnPlayOnPause之后再对播放器进行调用的话都会 崩溃。。

**Comment by lipangit** [comment]
保持关注，怎么解决



---原始邮件---
发件人: "AmoyJJ"<notifications@github.com&gt;
发送时间: 2020年4月22日(周三) 中午11:33
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 执行到releaseAllVideos()闪退 (#94)




 
加载视频中还未播放时。触发了 goOnPlayOnPause之后再对播放器进行调用的话都会 崩溃。。

**Comment by Liberations** [comment]
貌似解决了

**Comment by alphater** [comment]
> 貌似解决了

怎么解决的？
