### ISSUE TITLE
如何获取当前的播放时间，当前播放进度，没看到相关API可以获取上述相关信息

### ISSUE THREAD

**Issue by NSMichael** [Jzvd/JZVideo#99]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
继承jzvdstd复写onprogress函数



---原始邮件---
发件人: "Michael Geng"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 中午1:26
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 如何获取当前的播放时间，当前播放进度，没看到相关API可以获取上述相关信息 (#99)




 
**需求描述
 
**其他app是否实现
 
**截图或者小视频说明
